import type { Locale } from './catalog';

const en = {
  title: 'Agenda',
  subtitle: 'Appointments and tasks in one authorized operating view',
  agenda: 'Agenda',
  commercial: 'Commercial CRM',
  recruiting: 'Recruiting CRM',
  workspace: 'Connected workspace',
  connected: 'Persistent PostgreSQL data',
  locale: 'Language',
  theme: 'Theme',
  system: 'System',
  light: 'Light',
  dark: 'Dark',
  today: 'Today',
  day: 'Day',
  week: 'Week',
  list: 'Agenda list',
  previous: 'Previous range',
  next: 'Next range',
  date: 'Date',
  mine: 'Mine',
  all: 'All',
  type: 'Type',
  status: 'Status',
  appointment: 'Appointment',
  task: 'Task',
  scheduled: 'Scheduled',
  open: 'Open',
  completed: 'Completed',
  cancelled: 'Cancelled',
  pending: 'Pending',
  confirmed: 'Confirmed',
  declined: 'Declined',
  source: 'Context',
  manual: 'Standalone',
  commercial_crm: 'Commercial',
  recruiting_crm: 'Recruiting',
  loading: 'Loading agenda',
  empty: 'No agenda items yet',
  noResults: 'No items match these filters',
  forbidden: 'Access denied',
  forbiddenDetail: 'Your current permission does not allow Agenda access.',
  unavailable: 'Agenda is temporarily unavailable',
  notFound: 'This item is unavailable',
  conflict: 'This item changed. Latest data was loaded.',
  invalid: 'Review the entered values.',
  retry: 'Retry',
  clear: 'Clear filters',
  signIn: 'Sign in locally',
  sessionCode: 'Local session code',
  create: 'New item',
  createTask: 'Create task',
  createAppointment: 'Create appointment',
  detail: 'Agenda detail',
  close: 'Close',
  titleField: 'Title',
  summary: 'Summary',
  startsAt: 'Starts',
  endsAt: 'Ends',
  dueAt: 'Due',
  timezone: 'Timezone',
  priority: 'Priority',
  low: 'Low',
  normal: 'Normal',
  high: 'High',
  reminders: 'Internal RPT reminders',
  reminder15: '15 minutes before',
  reminder60: '1 hour before',
  reminder1440: '1 day before',
  confirmation: 'Confirmation',
  confirm: 'Confirm',
  decline: 'Decline',
  cancel: 'Cancel',
  reschedule: 'Reschedule',
  save: 'Save',
  complete: 'Complete task',
  recurrence: 'Recurrence',
  none: 'None',
  daily: 'Daily',
  weekly: 'Weekly',
  until: 'Until',
  weekdays: 'Weekdays',
  travel: 'Travel and preparation',
  origin: 'Origin label',
  destination: 'Destination label/address',
  travelMinutes: 'Travel minutes',
  preparationMinutes: 'Preparation minutes',
  history: 'History',
  success: 'Change saved',
  owner: 'Owner',
  linkedContext: 'Linked context',
  restrictedContext: 'Context hidden by policy',
  readonly: 'Projected CRM item · manage it in its source CRM',
  records: 'items',
  occurrence: 'Occurrence',
  series: 'Recurring series',
  internalOnly: 'Internal RPT reminder; no external notification is sent.',
  collapse: 'Collapse navigation',
  expand: 'Expand navigation',
  filters: 'Filters',
  invalidTime: 'This local time does not exist in the selected timezone.',
  created: 'Created',
  updated: 'Updated',
  rescheduled: 'Rescheduled',
  reminders_updated: 'Reminders updated',
  task_completed: 'Task completed',
};
const es: typeof en = {
  ...en,
  title: 'Agenda',
  subtitle: 'Citas y tareas en una vista operativa autorizada',
  agenda: 'Agenda',
  commercial: 'CRM Comercial',
  recruiting: 'CRM Reclutamiento',
  workspace: 'Espacio conectado',
  connected: 'Datos persistentes PostgreSQL',
  locale: 'Idioma',
  theme: 'Tema',
  system: 'Sistema',
  light: 'Claro',
  dark: 'Oscuro',
  today: 'Hoy',
  day: 'Día',
  week: 'Semana',
  list: 'Lista',
  previous: 'Rango anterior',
  next: 'Rango siguiente',
  date: 'Fecha',
  mine: 'Míos',
  all: 'Todos',
  type: 'Tipo',
  status: 'Estado',
  appointment: 'Cita',
  task: 'Tarea',
  scheduled: 'Programada',
  open: 'Abierta',
  completed: 'Completada',
  cancelled: 'Cancelada',
  pending: 'Pendiente',
  confirmed: 'Confirmada',
  declined: 'Rechazada',
  source: 'Contexto',
  manual: 'Independiente',
  commercial_crm: 'Comercial',
  recruiting_crm: 'Reclutamiento',
  loading: 'Cargando agenda',
  empty: 'Aún no hay elementos',
  noResults: 'Ningún elemento coincide con los filtros',
  forbidden: 'Acceso denegado',
  forbiddenDetail: 'Tu permiso actual no permite acceder a Agenda.',
  unavailable: 'Agenda no está disponible temporalmente',
  notFound: 'Este elemento no está disponible',
  conflict: 'El elemento cambió. Se cargaron los datos más recientes.',
  invalid: 'Revisa los valores ingresados.',
  retry: 'Reintentar',
  clear: 'Limpiar filtros',
  signIn: 'Iniciar sesión local',
  sessionCode: 'Código de sesión local',
  create: 'Nuevo elemento',
  createTask: 'Crear tarea',
  createAppointment: 'Crear cita',
  detail: 'Detalle de Agenda',
  close: 'Cerrar',
  titleField: 'Título',
  summary: 'Resumen',
  startsAt: 'Inicio',
  endsAt: 'Fin',
  dueAt: 'Vence',
  timezone: 'Zona horaria',
  priority: 'Prioridad',
  low: 'Baja',
  normal: 'Normal',
  high: 'Alta',
  reminders: 'Recordatorios internos RPT',
  reminder15: '15 minutos antes',
  reminder60: '1 hora antes',
  reminder1440: '1 día antes',
  confirmation: 'Confirmación',
  confirm: 'Confirmar',
  decline: 'Rechazar',
  cancel: 'Cancelar',
  reschedule: 'Reprogramar',
  save: 'Guardar',
  complete: 'Completar tarea',
  recurrence: 'Recurrencia',
  none: 'Ninguna',
  daily: 'Diaria',
  weekly: 'Semanal',
  until: 'Hasta',
  weekdays: 'Días de semana',
  travel: 'Traslado y preparación',
  origin: 'Origen',
  destination: 'Destino/dirección',
  travelMinutes: 'Minutos de traslado',
  preparationMinutes: 'Minutos de preparación',
  history: 'Historial',
  success: 'Cambio guardado',
  owner: 'Responsable',
  linkedContext: 'Contexto vinculado',
  restrictedContext: 'Contexto oculto por política',
  readonly: 'Elemento proyectado del CRM · adminístralo en su CRM de origen',
  records: 'elementos',
  occurrence: 'Ocurrencia',
  series: 'Serie recurrente',
  internalOnly: 'Recordatorio interno RPT; no se envía ninguna notificación externa.',
  collapse: 'Contraer navegación',
  expand: 'Expandir navegación',
  filters: 'Filtros',
  invalidTime: 'La hora local no existe en la zona horaria elegida.',
  created: 'Creado',
  updated: 'Actualizado',
  rescheduled: 'Reprogramado',
  reminders_updated: 'Recordatorios actualizados',
  task_completed: 'Tarea completada',
};
const fr: typeof en = {
  ...en,
  subtitle: 'Rendez-vous et tâches dans une vue opérationnelle autorisée',
  commercial: 'CRM Commercial',
  recruiting: 'CRM Recrutement',
  workspace: 'Espace connecté',
  connected: 'Données PostgreSQL persistantes',
  locale: 'Langue',
  theme: 'Thème',
  system: 'Système',
  light: 'Clair',
  dark: 'Sombre',
  today: "Aujourd'hui",
  day: 'Jour',
  week: 'Semaine',
  list: 'Liste',
  previous: 'Période précédente',
  next: 'Période suivante',
  date: 'Date',
  mine: 'Les miens',
  all: 'Tous',
  type: 'Type',
  status: 'Statut',
  appointment: 'Rendez-vous',
  task: 'Tâche',
  scheduled: 'Planifié',
  open: 'Ouverte',
  completed: 'Terminée',
  cancelled: 'Annulée',
  pending: 'En attente',
  confirmed: 'Confirmé',
  declined: 'Refusé',
  source: 'Contexte',
  manual: 'Autonome',
  commercial_crm: 'Commercial',
  recruiting_crm: 'Recrutement',
  loading: 'Chargement de l’agenda',
  empty: 'Aucun élément',
  noResults: 'Aucun résultat',
  forbidden: 'Accès refusé',
  forbiddenDetail: "Votre autorisation actuelle ne permet pas l'accès à l’Agenda.",
  unavailable: 'Agenda temporairement indisponible',
  notFound: 'Cet élément est indisponible',
  conflict: 'Cet élément a changé. Les dernières données ont été chargées.',
  retry: 'Réessayer',
  clear: 'Effacer',
  signIn: 'Connexion locale',
  sessionCode: 'Code de session locale',
  create: 'Nouvel élément',
  createTask: 'Créer une tâche',
  createAppointment: 'Créer un rendez-vous',
  detail: 'Détail Agenda',
  close: 'Fermer',
  titleField: 'Titre',
  summary: 'Résumé',
  startsAt: 'Début',
  endsAt: 'Fin',
  dueAt: 'Échéance',
  timezone: 'Fuseau horaire',
  priority: 'Priorité',
  low: 'Basse',
  normal: 'Normale',
  high: 'Haute',
  reminders: 'Rappels RPT internes',
  confirmation: 'Confirmation',
  confirm: 'Confirmer',
  decline: 'Refuser',
  cancel: 'Annuler',
  reschedule: 'Replanifier',
  save: 'Enregistrer',
  complete: 'Terminer la tâche',
  recurrence: 'Récurrence',
  none: 'Aucune',
  daily: 'Quotidienne',
  weekly: 'Hebdomadaire',
  until: "Jusqu'au",
  weekdays: 'Jours de semaine',
  travel: 'Déplacement et préparation',
  origin: 'Origine',
  destination: 'Destination/adresse',
  travelMinutes: 'Minutes de trajet',
  preparationMinutes: 'Minutes de préparation',
  history: 'Historique',
  success: 'Modification enregistrée',
  owner: 'Responsable',
  linkedContext: 'Contexte lié',
  restrictedContext: 'Contexte masqué par la politique',
  readonly: 'Élément CRM projeté · gérez-le dans son CRM source',
  records: 'éléments',
  occurrence: 'Occurrence',
  series: 'Série récurrente',
  internalOnly: "Rappel RPT interne ; aucune notification externe n'est envoyée.",
  filters: 'Filtres',
  invalidTime: "Cette heure locale n'existe pas dans le fuseau choisi.",
  created: 'Créé',
  updated: 'Mis à jour',
  rescheduled: 'Replanifié',
  reminders_updated: 'Rappels mis à jour',
  task_completed: 'Tâche terminée',
};
const pt: typeof en = {
  ...en,
  subtitle: 'Compromissos e tarefas em uma visão operacional autorizada',
  commercial: 'CRM Comercial',
  recruiting: 'CRM Recrutamento',
  workspace: 'Espaço conectado',
  connected: 'Dados PostgreSQL persistentes',
  locale: 'Idioma',
  theme: 'Tema',
  system: 'Sistema',
  light: 'Claro',
  dark: 'Escuro',
  today: 'Hoje',
  day: 'Dia',
  week: 'Semana',
  list: 'Lista',
  previous: 'Período anterior',
  next: 'Próximo período',
  date: 'Data',
  mine: 'Meus',
  all: 'Todos',
  type: 'Tipo',
  status: 'Status',
  appointment: 'Compromisso',
  task: 'Tarefa',
  scheduled: 'Agendado',
  open: 'Aberta',
  completed: 'Concluída',
  cancelled: 'Cancelada',
  pending: 'Pendente',
  confirmed: 'Confirmado',
  declined: 'Recusado',
  source: 'Contexto',
  manual: 'Independente',
  commercial_crm: 'Comercial',
  recruiting_crm: 'Recrutamento',
  loading: 'Carregando agenda',
  empty: 'Ainda não há itens',
  noResults: 'Nenhum item corresponde aos filtros',
  forbidden: 'Acesso negado',
  forbiddenDetail: 'Sua permissão atual não permite acesso à Agenda.',
  unavailable: 'Agenda temporariamente indisponível',
  notFound: 'Este item não está disponível',
  conflict: 'O item mudou. Os dados mais recentes foram carregados.',
  retry: 'Tentar novamente',
  clear: 'Limpar filtros',
  signIn: 'Iniciar sessão local',
  sessionCode: 'Código de sessão local',
  create: 'Novo item',
  createTask: 'Criar tarefa',
  createAppointment: 'Criar compromisso',
  detail: 'Detalhe da Agenda',
  close: 'Fechar',
  titleField: 'Título',
  summary: 'Resumo',
  startsAt: 'Início',
  endsAt: 'Fim',
  dueAt: 'Vence',
  timezone: 'Fuso horário',
  priority: 'Prioridade',
  low: 'Baixa',
  normal: 'Normal',
  high: 'Alta',
  reminders: 'Lembretes internos RPT',
  confirmation: 'Confirmação',
  confirm: 'Confirmar',
  decline: 'Recusar',
  cancel: 'Cancelar',
  reschedule: 'Reagendar',
  save: 'Salvar',
  complete: 'Concluir tarefa',
  recurrence: 'Recorrência',
  none: 'Nenhuma',
  daily: 'Diária',
  weekly: 'Semanal',
  until: 'Até',
  weekdays: 'Dias da semana',
  travel: 'Deslocamento e preparação',
  origin: 'Origem',
  destination: 'Destino/endereço',
  travelMinutes: 'Minutos de deslocamento',
  preparationMinutes: 'Minutos de preparação',
  history: 'Histórico',
  success: 'Alteração salva',
  owner: 'Responsável',
  linkedContext: 'Contexto vinculado',
  restrictedContext: 'Contexto oculto pela política',
  readonly: 'Item projetado do CRM · gerencie no CRM de origem',
  records: 'itens',
  occurrence: 'Ocorrência',
  series: 'Série recorrente',
  internalOnly: 'Lembrete interno RPT; nenhuma notificação externa é enviada.',
  filters: 'Filtros',
  invalidTime: 'Este horário local não existe no fuso selecionado.',
  created: 'Criado',
  updated: 'Atualizado',
  rescheduled: 'Reagendado',
  reminders_updated: 'Lembretes atualizados',
  task_completed: 'Tarefa concluída',
};

export const agendaCatalogs: Record<Locale, Record<string, string>> = { es, en, fr, pt };
