export const es = {
  title: 'CRM Comercial',
  subtitle: 'Tu cartera operativa. Cada relación, un siguiente paso.',
  fixture: 'Referencia Foundation · Todos los datos son ficticios',
  workspace: 'Cartera personal',
  reference: 'Referencia CRM',
  lab: 'Componentes',
  collapse: 'Contraer navegación',
  expand: 'Expandir navegación',
  search: 'Buscar oportunidades',
  searchHint: 'Buscar por nombre…',
  theme: 'Tema',
  language: 'Idioma',
  system: 'Sistema',
  light: 'Claro',
  dark: 'Oscuro',
  all: 'Todas',
  mine: 'Mías',
  due: 'Por atender',
  table: 'Tabla',
  kanban: 'Kanban',
  stage: 'Etapa',
  source: 'Origen',
  owner: 'Responsable',
  self: 'Mi cartera',
  delegated: 'Acceso delegado',
  referral: 'Referido',
  event: 'Evento',
  new: 'Por contactar',
  appointment: 'Cita programada',
  demo: 'Demo realizada',
  followup: 'Seguimiento',
  next: 'Siguiente acción',
  when: 'Próxima fecha',
  activity: 'Actividades',
  name: 'Persona / oportunidad',
  filters: 'Filtros',
  clear: 'Limpiar filtros',
  saveView: 'Guardar vista',
  viewName: 'Nombre de la vista',
  save: 'Guardar',
  close: 'Cerrar',
  comfortable: 'Cómoda',
  compact: 'Compacta',
  density: 'Densidad',
  create: 'Añadir ejemplo ficticio',
  record: 'Registrar actividad de prueba',
  confirm: 'Confirmar cita',
  contact: 'Preparar contacto',
  follow: 'Programar seguimiento',
  select: 'Seleccionar',
  selected: 'seleccionadas',
  selectionAction: 'Registrar actividad en selección',
  selectionClear: 'Quitar selección',
  records: 'oportunidades',
  prev: 'Anterior',
  nextPage: 'Siguiente',
  page: 'Página',
  noResults: 'Sin resultados con estos filtros',
  noResultsDetail: 'Prueba otra búsqueda o limpia los filtros.',
  permission: 'Acceso no disponible',
  permissionDetail: 'Tu rol o delegación no permite abrir esta vista.',
  error: 'No pudimos cargar esta vista',
  errorDetail: 'No se guardaron cambios. Puedes reintentar. Soporte: reference-test.',
  retry: 'Reintentar',
  empty: 'Tu cartera está lista para comenzar',
  emptyDetail: 'Añade un ejemplo para explorar esta referencia.',
  loading: 'Cargando oportunidades…',
  offline: 'Sin conexión · Solo ejemplos locales; no se sincronizarán datos.',
  degraded: 'Integración no disponible · La cartera de ejemplo sigue disponible.',
  labTitle: 'Component Lab',
  labDetail: 'Contratos visuales compartidos · Sin servicios productivos',
  state: 'Estado de prueba',
  ready: 'Disponible',
  volume: 'Cantidad de ejemplos',
  examplesOnly: 'Este registro es ficticio. No envía mensajes ni crea pedidos reales.',
  timeline: 'Actividad reciente',
  localEvent: 'Actividad de prueba registrada',
  sourceLabel: 'Fuente: fixture local — no oficial',
  details: 'Contexto',
  notes: 'Sigue el próximo paso sin perder de vista el historial.',
  shown: 'Mostrando',
  of: 'de',
  columns: 'Mostrar origen',
  saved: 'Vista guardada en esta sesión',
  privateView: 'Vista privada · No contiene permisos',
  status401: 'Inicia sesión para continuar',
  status429: 'Espera un momento antes de reintentar',
};
export type Catalog = { [K in keyof typeof es]: string };
export type Locale = 'es' | 'en' | 'fr' | 'pt';
export const catalogs: Record<Locale, Catalog> = {
  es,
  en: {
    ...es,
    title: 'Commercial CRM',
    subtitle: 'Your working portfolio. Every relationship, a next step.',
    fixture: 'Foundation reference · All data is fictional',
    workspace: 'Personal portfolio',
    reference: 'CRM reference',
    lab: 'Components',
    collapse: 'Collapse navigation',
    expand: 'Expand navigation',
    search: 'Search opportunities',
    searchHint: 'Search by name…',
    theme: 'Theme',
    language: 'Language',
    system: 'System',
    light: 'Light',
    dark: 'Dark',
    all: 'All',
    mine: 'Mine',
    due: 'Needs attention',
    table: 'Table',
    kanban: 'Kanban',
    stage: 'Stage',
    source: 'Source',
    owner: 'Owner',
    self: 'My portfolio',
    delegated: 'Delegated access',
    referral: 'Referral',
    event: 'Event',
    new: 'To contact',
    appointment: 'Appointment',
    demo: 'Demo completed',
    followup: 'Follow-up',
    next: 'Next action',
    when: 'Next date',
    activity: 'Activities',
    name: 'Person / opportunity',
    filters: 'Filters',
    clear: 'Clear filters',
    saveView: 'Save view',
    viewName: 'View name',
    save: 'Save',
    close: 'Close',
    comfortable: 'Comfortable',
    compact: 'Compact',
    density: 'Density',
    create: 'Add fictional example',
    record: 'Record test activity',
    confirm: 'Confirm appointment',
    contact: 'Prepare contact',
    follow: 'Schedule follow-up',
    select: 'Select',
    selected: 'selected',
    selectionAction: 'Record activity for selection',
    selectionClear: 'Clear selection',
    records: 'opportunities',
    prev: 'Previous',
    nextPage: 'Next',
    page: 'Page',
    noResults: 'No results with these filters',
    noResultsDetail: 'Try another search or clear the filters.',
    permission: 'Access unavailable',
    permissionDetail: 'Your role or delegation does not allow this view.',
    error: 'We could not load this view',
    errorDetail: 'No changes saved. You can retry. Support: reference-test.',
    retry: 'Retry',
    empty: 'Your portfolio is ready to begin',
    emptyDetail: 'Add an example to explore this reference.',
    loading: 'Loading opportunities…',
    offline: 'Offline · Local examples only; no data will sync.',
    degraded: 'Integration unavailable · Example portfolio remains available.',
    labTitle: 'Component Lab',
    labDetail: 'Shared visual contracts · No production services',
    state: 'Test state',
    ready: 'Ready',
    volume: 'Example count',
    examplesOnly: 'Fictional record. No messages or real orders are sent.',
    timeline: 'Recent activity',
    localEvent: 'Test activity recorded',
    sourceLabel: 'Source: local fixture — not official',
    details: 'Context',
    notes: 'Follow the next step without losing history.',
    shown: 'Showing',
    of: 'of',
    columns: 'Show source',
    saved: 'View saved for this session',
    privateView: 'Private view · Contains no permissions',
    status401: 'Sign in to continue',
    status429: 'Please wait before trying again',
  },
  fr: {
    ...es,
    title: 'CRM Commercial',
    subtitle: 'Votre portefeuille opérationnel. Une prochaine étape pour chaque relation.',
    fixture: 'Référence Foundation · Toutes les données sont fictives',
    workspace: 'Portefeuille personnel',
    reference: 'Référence CRM',
    lab: 'Composants',
    collapse: 'Réduire la navigation',
    expand: 'Développer la navigation',
    search: 'Rechercher des opportunités',
    searchHint: 'Rechercher par nom…',
    theme: 'Thème',
    language: 'Langue',
    system: 'Système',
    light: 'Clair',
    dark: 'Sombre',
    all: 'Toutes',
    mine: 'Les miennes',
    due: 'À traiter',
    table: 'Tableau',
    kanban: 'Kanban',
    stage: 'Étape',
    source: 'Origine',
    owner: 'Responsable',
    self: 'Mon portefeuille',
    delegated: 'Accès délégué',
    referral: 'Recommandation',
    event: 'Événement',
    new: 'À contacter',
    appointment: 'Rendez-vous programmé',
    demo: 'Démonstration réalisée',
    followup: 'Suivi',
    next: 'Prochaine action',
    when: 'Prochaine date',
    activity: 'Activités',
    name: 'Personne / opportunité',
    filters: 'Filtres',
    clear: 'Effacer les filtres',
    saveView: 'Enregistrer la vue',
    viewName: 'Nom de la vue',
    save: 'Enregistrer',
    close: 'Fermer',
    comfortable: 'Confortable',
    compact: 'Compacte',
    density: 'Densité',
    create: 'Ajouter un exemple fictif',
    record: 'Enregistrer une activité de test',
    confirm: 'Confirmer le rendez-vous',
    contact: 'Préparer le contact',
    follow: 'Programmer un suivi',
    select: 'Sélectionner',
    selected: 'sélectionnées',
    selectionAction: 'Enregistrer une activité pour la sélection',
    selectionClear: 'Effacer la sélection',
    records: 'opportunités',
    prev: 'Précédente',
    nextPage: 'Suivante',
    page: 'Page',
    noResults: 'Aucun résultat pour ces filtres',
    noResultsDetail: 'Essayez une autre recherche ou effacez les filtres.',
    permission: 'Accès indisponible',
    permissionDetail: 'Votre rôle ou délégation ne permet pas cette vue.',
    error: 'Impossible de charger cette vue',
    errorDetail: 'Aucune modification enregistrée. Réessayez. Support : reference-test.',
    retry: 'Réessayer',
    empty: 'Votre portefeuille est prêt',
    emptyDetail: 'Ajoutez un exemple pour explorer cette référence.',
    loading: 'Chargement des opportunités…',
    offline: 'Hors connexion · Exemples locaux uniquement ; aucune synchronisation.',
    degraded: 'Intégration indisponible · Le portefeuille fictif reste disponible.',
    labTitle: 'Component Lab',
    labDetail: 'Contrats visuels partagés · Aucun service de production',
    state: 'État de test',
    ready: 'Disponible',
    volume: 'Nombre d’exemples',
    examplesOnly: 'Fiche fictive. Aucun message ni commande réelle.',
    timeline: 'Activité récente',
    localEvent: 'Activité de test enregistrée',
    sourceLabel: 'Source : exemple local — non officiel',
    details: 'Contexte',
    notes: 'Suivez la prochaine étape sans perdre l’historique.',
    shown: 'Affichage',
    of: 'sur',
    columns: 'Afficher l’origine',
    saved: 'Vue enregistrée pour cette session',
    privateView: 'Vue privée · Sans autorisations',
    status401: 'Connectez-vous pour continuer',
    status429: 'Patientez avant de réessayer',
  },
  pt: {
    ...es,
    title: 'CRM Comercial',
    subtitle: 'Sua carteira operacional. Cada relação, um próximo passo.',
    fixture: 'Referência Foundation · Todos os dados são fictícios',
    workspace: 'Carteira pessoal',
    reference: 'Referência CRM',
    lab: 'Componentes',
    collapse: 'Recolher navegação',
    expand: 'Expandir navegação',
    search: 'Buscar oportunidades',
    searchHint: 'Buscar por nome…',
    theme: 'Tema',
    language: 'Idioma',
    system: 'Sistema',
    light: 'Claro',
    dark: 'Escuro',
    all: 'Todas',
    mine: 'Minhas',
    due: 'Precisam de atenção',
    table: 'Tabela',
    kanban: 'Kanban',
    stage: 'Etapa',
    source: 'Origem',
    owner: 'Responsável',
    self: 'Minha carteira',
    delegated: 'Acesso delegado',
    referral: 'Indicação',
    event: 'Evento',
    new: 'A contatar',
    appointment: 'Reunião marcada',
    demo: 'Demonstração realizada',
    followup: 'Acompanhamento',
    next: 'Próxima ação',
    when: 'Próxima data',
    activity: 'Atividades',
    name: 'Pessoa / oportunidade',
    filters: 'Filtros',
    clear: 'Limpar filtros',
    saveView: 'Salvar visualização',
    viewName: 'Nome da visualização',
    save: 'Salvar',
    close: 'Fechar',
    comfortable: 'Confortável',
    compact: 'Compacta',
    density: 'Densidade',
    create: 'Adicionar exemplo fictício',
    record: 'Registrar atividade de teste',
    confirm: 'Confirmar reunião',
    contact: 'Preparar contato',
    follow: 'Agendar acompanhamento',
    select: 'Selecionar',
    selected: 'selecionadas',
    selectionAction: 'Registrar atividade na seleção',
    selectionClear: 'Limpar seleção',
    records: 'oportunidades',
    prev: 'Anterior',
    nextPage: 'Próxima',
    page: 'Página',
    noResults: 'Nenhum resultado com estes filtros',
    noResultsDetail: 'Tente outra busca ou limpe os filtros.',
    permission: 'Acesso indisponível',
    permissionDetail: 'Seu papel ou delegação não permite esta visualização.',
    error: 'Não foi possível carregar a visualização',
    errorDetail: 'Nenhuma alteração salva. Tente novamente. Suporte: reference-test.',
    retry: 'Tentar novamente',
    empty: 'Sua carteira está pronta para começar',
    emptyDetail: 'Adicione um exemplo para explorar esta referência.',
    loading: 'Carregando oportunidades…',
    offline: 'Sem conexão · Apenas exemplos locais; nenhum dado será sincronizado.',
    degraded: 'Integração indisponível · A carteira de exemplo continua disponível.',
    labTitle: 'Component Lab',
    labDetail: 'Contratos visuais compartilhados · Sem serviços de produção',
    state: 'Estado de teste',
    ready: 'Disponível',
    volume: 'Quantidade de exemplos',
    examplesOnly: 'Registro fictício. Não envia mensagens nem cria pedidos reais.',
    timeline: 'Atividade recente',
    localEvent: 'Atividade de teste registrada',
    sourceLabel: 'Fonte: exemplo local — não oficial',
    details: 'Contexto',
    notes: 'Siga o próximo passo sem perder o histórico.',
    shown: 'Mostrando',
    of: 'de',
    columns: 'Mostrar origem',
    saved: 'Visualização salva nesta sessão',
    privateView: 'Visualização privada · Sem permissões',
    status401: 'Entre para continuar',
    status429: 'Aguarde antes de tentar novamente',
  },
};
