import type { Locale } from './catalog';
const importEs = {
  importAction: 'Importar',
  importTitle: 'Importar oportunidades',
  fileHelp: 'CSV o XLSX · máximo 100 filas y 512 KB. La vista previa no guarda datos.',
  chooseFile: 'Archivo',
  previewImport: 'Generar vista previa',
  confirmImport: 'Confirmar importación',
  importError: 'No se pudo procesar la importación.',
  previewSummary: 'Resumen de vista previa',
  totalRows: 'Filas totales',
  validRows: 'Filas válidas',
  invalidRows: 'Filas inválidas',
  newPersons: 'Personas nuevas',
  linkedPersons: 'Personas enlazadas',
  conflicts: 'Conflictos',
  opportunitiesToCreate: 'Oportunidades a crear',
  errors: 'Errores',
  row: 'Fila',
  file: 'Archivo',
  result: 'Resultado',
  completed: 'Importación completada',
  createdPersons: 'Personas creadas',
  createdOpportunities: 'Oportunidades creadas',
  rejectedRows: 'Filas rechazadas',
  conflictRows: 'Filas con conflicto',
  importCompleted: 'Importación completada y lista actualizada.',
  invalid_file: 'Archivo inválido',
  invalid_header: 'Encabezado inválido',
  invalid_row: 'Fila inválida',
  duplicate_identity: 'Identidad duplicada',
  ambiguous_identity: 'Identidad ambigua',
  forbidden: 'Sin permiso',
  cross_tenant: 'Otro tenant',
  conflict: 'Conflicto',
  unsupported_value: 'Valor no admitido',
  identity: 'Identidad',
  file_size: 'El tamaño no está permitido',
  macro_or_legacy_excel_not_supported: 'Excel con macros o formato antiguo no admitido',
  format_mismatch: 'El contenido no coincide con un archivo CSV o XLSX admitido',
  csv_must_be_utf8: 'El CSV debe usar UTF-8',
  nul_byte: 'El archivo contiene bytes no admitidos',
  invalid_csv_quote: 'Comillas CSV inválidas',
  unterminated_csv_quote: 'Comillas CSV sin cerrar',
  unsafe_xlsx_package: 'El libro contiene elementos no seguros',
  invalid_xlsx_package: 'Paquete XLSX inválido',
  missing_xlsx_content_types: 'Estructura XLSX incompleta',
  macro_enabled_xlsx: 'Los libros con macros no están permitidos',
  xlsx_formulas_not_supported: 'Las fórmulas no están permitidas',
  invalid_xlsx: 'Libro XLSX inválido',
  header_and_rows_required: 'Se requieren encabezados y filas',
  row_limit_exceeded: 'Se excedió el límite de filas',
  column_limit: 'Se excedió el límite de columnas',
  unsupported_or_missing_header: 'Falta un encabezado requerido o existe uno desconocido',
  text_required: 'Debe ser texto',
  cell_too_long: 'El valor es demasiado largo',
  formula_like_value: 'No se permiten valores similares a fórmulas',
  identity_required: 'Se requiere email o teléfono',
  referrer_requires_referral: 'El referidor requiere source referral',
  exact_identity_conflict: 'La identidad exacta es ambigua',
  inconsistent_identity: 'Los identificadores apuntan a registros distintos',
  referrer_conflict: 'El referidor es ambiguo',
  referrer_not_found: 'No se encontró un referidor autorizado',
  duplicate_batch_row: 'La oportunidad está duplicada en el archivo',
};
type ImportCatalog = { [K in keyof typeof importEs]: string };
const importEn: ImportCatalog = {
  importAction: 'Import',
  importTitle: 'Import opportunities',
  fileHelp: 'CSV or XLSX · up to 100 rows and 512 KB. Preview does not save data.',
  chooseFile: 'File',
  previewImport: 'Generate preview',
  confirmImport: 'Confirm import',
  importError: 'The import could not be processed.',
  previewSummary: 'Preview summary',
  totalRows: 'Total rows',
  validRows: 'Valid rows',
  invalidRows: 'Invalid rows',
  newPersons: 'New people',
  linkedPersons: 'Linked people',
  conflicts: 'Conflicts',
  opportunitiesToCreate: 'Opportunities to create',
  errors: 'Errors',
  row: 'Row',
  file: 'File',
  result: 'Result',
  completed: 'Import completed',
  createdPersons: 'People created',
  createdOpportunities: 'Opportunities created',
  rejectedRows: 'Rejected rows',
  conflictRows: 'Conflict rows',
  importCompleted: 'Import completed and list refreshed.',
  invalid_file: 'Invalid file',
  invalid_header: 'Invalid header',
  invalid_row: 'Invalid row',
  duplicate_identity: 'Duplicate identity',
  ambiguous_identity: 'Ambiguous identity',
  forbidden: 'Forbidden',
  cross_tenant: 'Different tenant',
  conflict: 'Conflict',
  unsupported_value: 'Unsupported value',
  identity: 'Identity',
  file_size: 'File size is not allowed',
  macro_or_legacy_excel_not_supported: 'Macro-enabled or legacy Excel is unsupported',
  format_mismatch: 'Content does not match a supported CSV or XLSX file',
  csv_must_be_utf8: 'CSV must use UTF-8',
  nul_byte: 'File contains unsupported bytes',
  invalid_csv_quote: 'Invalid CSV quoting',
  unterminated_csv_quote: 'Unterminated CSV quote',
  unsafe_xlsx_package: 'Workbook contains unsafe elements',
  invalid_xlsx_package: 'Invalid XLSX package',
  missing_xlsx_content_types: 'Incomplete XLSX structure',
  macro_enabled_xlsx: 'Macro-enabled workbooks are not allowed',
  xlsx_formulas_not_supported: 'Formulas are not allowed',
  invalid_xlsx: 'Invalid XLSX workbook',
  header_and_rows_required: 'Headers and rows are required',
  row_limit_exceeded: 'Row limit exceeded',
  column_limit: 'Column limit exceeded',
  unsupported_or_missing_header: 'A required header is missing or an unknown header is present',
  text_required: 'Must be text',
  cell_too_long: 'Value is too long',
  formula_like_value: 'Formula-like values are not allowed',
  identity_required: 'Email or phone is required',
  referrer_requires_referral: 'Referrer requires referral source',
  exact_identity_conflict: 'Exact identity is ambiguous',
  inconsistent_identity: 'Identifiers point to different records',
  referrer_conflict: 'Referrer is ambiguous',
  referrer_not_found: 'No authorized referrer was found',
  duplicate_batch_row: 'Opportunity is duplicated in the file',
};
const importFr: ImportCatalog = {
  ...importEn,
  importAction: 'Importer',
  importTitle: 'Importer des opportunités',
  fileHelp: 'CSV ou XLSX · 100 lignes et 512 Ko maximum. L’aperçu n’enregistre rien.',
  chooseFile: 'Fichier',
  previewImport: 'Générer l’aperçu',
  confirmImport: 'Confirmer l’importation',
  importError: 'L’importation n’a pas pu être traitée.',
  previewSummary: 'Résumé de l’aperçu',
  totalRows: 'Lignes totales',
  validRows: 'Lignes valides',
  invalidRows: 'Lignes invalides',
  newPersons: 'Nouvelles personnes',
  linkedPersons: 'Personnes liées',
  conflicts: 'Conflits',
  opportunitiesToCreate: 'Opportunités à créer',
  errors: 'Erreurs',
  row: 'Ligne',
  file: 'Fichier',
  result: 'Résultat',
  completed: 'Importation terminée',
  createdPersons: 'Personnes créées',
  createdOpportunities: 'Opportunités créées',
  rejectedRows: 'Lignes rejetées',
  conflictRows: 'Lignes en conflit',
  importCompleted: 'Importation terminée et liste actualisée.',
};
const importPt: ImportCatalog = {
  ...importEn,
  importAction: 'Importar',
  importTitle: 'Importar oportunidades',
  fileHelp: 'CSV ou XLSX · até 100 linhas e 512 KB. A prévia não salva dados.',
  chooseFile: 'Arquivo',
  previewImport: 'Gerar prévia',
  confirmImport: 'Confirmar importação',
  importError: 'Não foi possível processar a importação.',
  previewSummary: 'Resumo da prévia',
  totalRows: 'Linhas totais',
  validRows: 'Linhas válidas',
  invalidRows: 'Linhas inválidas',
  newPersons: 'Novas pessoas',
  linkedPersons: 'Pessoas vinculadas',
  conflicts: 'Conflitos',
  opportunitiesToCreate: 'Oportunidades a criar',
  errors: 'Erros',
  row: 'Linha',
  file: 'Arquivo',
  result: 'Resultado',
  completed: 'Importação concluída',
  createdPersons: 'Pessoas criadas',
  createdOpportunities: 'Oportunidades criadas',
  rejectedRows: 'Linhas rejeitadas',
  conflictRows: 'Linhas em conflito',
  importCompleted: 'Importação concluída e lista atualizada.',
};
const es = {
  ...importEs,
  reference: 'CRM Comercial',
  sort: 'Ordenar por',
  updated: 'Última actualización',
  direction: 'Dirección',
  asc: 'Ascendente',
  desc: 'Descendente',
  visibleColumns: 'Columnas visibles',
  noPermissions: 'Guardar o compartir una vista no concede permisos sobre los datos.',
  fixture: 'CRM conectado · PostgreSQL · Datos sintéticos',
  sourceLabel: 'Fuente: PostgreSQL de desarrollo — no oficial',
  saved: 'Vista guardada en PostgreSQL',
  empty: 'Aún no tienes oportunidades activas',
  emptyDetail: 'Cuando tengas acceso a una oportunidad, aparecerá aquí.',
  errorDetail: 'No se pudo completar la solicitud. Reintenta sin conexión de respaldo a ejemplos.',
  contacted: 'Contactado',
  proposal: 'Propuesta',
  pending_approval: 'Pendiente de aprobación',
  won_simulated: 'Ganada — simulación',
  won: 'Ganada oficial',
  lost: 'Perdida',
  manual: 'Manual',
  import: 'Importación',
  status: 'Estado',
  open: 'Abiertas',
  closed: 'Cerradas',
  priority: 'Prioridad',
  normal: 'Normal',
  high: 'Alta',
  inactive: 'Sin actividad · 7 días',
  visibility: 'Visibilidad',
  private: 'Privada',
  team: 'Equipo',
  shared: 'Compartida',
  recipients: 'Destinatarios autorizados (UUID separados por coma)',
  sessionCode: 'Código de sesión local',
  signIn: 'Iniciar sesión local',
  detailPending: 'Detalle y acciones persistentes disponibles según tu autorización.',
  add_collaborator: 'Añadir colaborador',
  remove_collaborator: 'Quitar colaborador',
  collaborators: 'Colaboradores',
  activity: 'Registrar actividad',
  activities: 'Actividades',
  call: 'Llamada interna',
  message: 'Mensaje interno',
  occurredAt: 'Fecha de la actividad',
  summary: 'Resumen',
  userId: 'Usuario autorizado (UUID)',
  access: 'Alcance',
  read: 'Solo lectura',
  update: 'Lectura y actualización',
  until: 'Acceso hasta',
  set_referral: 'Registrar referido',
  referrer: 'Persona referidora',
  referrerPersonId: 'Persona referidora (UUID)',
};
type CrmCatalog = { [K in keyof typeof es]: string };
export const crmCatalogs: Record<Locale, CrmCatalog> = {
  es,
  en: {
    ...importEn,
    reference: 'Commercial CRM',
    sort: 'Sort by',
    updated: 'Last updated',
    direction: 'Direction',
    asc: 'Ascending',
    desc: 'Descending',
    visibleColumns: 'Visible columns',
    noPermissions: 'Saving or sharing a view does not grant data access.',
    fixture: 'Connected CRM · PostgreSQL · Synthetic data',
    sourceLabel: 'Source: development PostgreSQL — unofficial',
    saved: 'View saved in PostgreSQL',
    empty: 'You do not have active opportunities yet',
    emptyDetail: 'When an opportunity is available to you, it will appear here.',
    errorDetail: 'The request failed. Retry; example data is never used as fallback.',
    contacted: 'Contacted',
    proposal: 'Proposal',
    pending_approval: 'Pending approval',
    won_simulated: 'Won — simulation',
    won: 'Official won',
    lost: 'Lost',
    manual: 'Manual',
    import: 'Import',
    status: 'Status',
    open: 'Open',
    closed: 'Closed',
    priority: 'Priority',
    normal: 'Normal',
    high: 'High',
    inactive: 'Inactive · 7 days',
    visibility: 'Visibility',
    private: 'Private',
    team: 'Team',
    shared: 'Shared',
    recipients: 'Authorized recipients (comma-separated UUIDs)',
    sessionCode: 'Local session code',
    signIn: 'Start local session',
    detailPending: 'Persistent details and actions are available according to your authorization.',
    add_collaborator: 'Add collaborator',
    remove_collaborator: 'Remove collaborator',
    collaborators: 'Collaborators',
    activity: 'Record activity',
    activities: 'Activities',
    call: 'Internal call',
    message: 'Internal message',
    occurredAt: 'Activity date',
    summary: 'Summary',
    userId: 'Authorized user (UUID)',
    access: 'Scope',
    read: 'Read only',
    update: 'Read and update',
    until: 'Access until',
    set_referral: 'Set referral',
    referrer: 'Referrer Person',
    referrerPersonId: 'Referrer Person (UUID)',
  },
  fr: {
    ...importFr,
    reference: 'CRM Commercial',
    sort: 'Trier par',
    updated: 'Dernière mise à jour',
    direction: 'Direction',
    asc: 'Croissant',
    desc: 'Décroissant',
    visibleColumns: 'Colonnes visibles',
    noPermissions: 'Enregistrer ou partager une vue ne donne aucun droit sur les données.',
    fixture: 'CRM connecté · PostgreSQL · Données synthétiques',
    sourceLabel: 'Source : PostgreSQL de développement — non officiel',
    saved: 'Vue enregistrée dans PostgreSQL',
    empty: 'Vous n’avez pas encore d’opportunités actives',
    emptyDetail: 'Lorsqu’une opportunité vous sera accessible, elle apparaîtra ici.',
    errorDetail: 'La requête a échoué. Réessayez ; les exemples ne remplacent jamais les données.',
    contacted: 'Contacté',
    proposal: 'Proposition',
    pending_approval: 'En attente d’approbation',
    won_simulated: 'Gagnée — simulation',
    won: 'Gagnée officielle',
    lost: 'Perdue',
    manual: 'Manuel',
    import: 'Importation',
    status: 'Statut',
    open: 'Ouvertes',
    closed: 'Fermées',
    priority: 'Priorité',
    normal: 'Normale',
    high: 'Haute',
    inactive: 'Inactive · 7 jours',
    visibility: 'Visibilité',
    private: 'Privée',
    team: 'Équipe',
    shared: 'Partagée',
    recipients: 'Destinataires autorisés (UUID séparés par des virgules)',
    sessionCode: 'Code de session locale',
    signIn: 'Ouvrir une session locale',
    detailPending: 'Les détails et actions persistants sont disponibles selon votre autorisation.',
    add_collaborator: 'Ajouter un collaborateur',
    remove_collaborator: 'Retirer le collaborateur',
    collaborators: 'Collaborateurs',
    activity: 'Enregistrer une activité',
    activities: 'Activités',
    call: 'Appel interne',
    message: 'Message interne',
    occurredAt: 'Date de l’activité',
    summary: 'Résumé',
    userId: 'Utilisateur autorisé (UUID)',
    access: 'Périmètre',
    read: 'Lecture seule',
    update: 'Lecture et modification',
    until: 'Accès jusqu’au',
    set_referral: 'Définir la recommandation',
    referrer: 'Personne référente',
    referrerPersonId: 'Personne référente (UUID)',
  },
  pt: {
    ...importPt,
    reference: 'CRM Comercial',
    sort: 'Ordenar por',
    updated: 'Última atualização',
    direction: 'Direção',
    asc: 'Crescente',
    desc: 'Decrescente',
    visibleColumns: 'Colunas visíveis',
    noPermissions: 'Salvar ou compartilhar uma visualização não concede acesso aos dados.',
    fixture: 'CRM conectado · PostgreSQL · Dados sintéticos',
    sourceLabel: 'Fonte: PostgreSQL de desenvolvimento — não oficial',
    saved: 'Visualização salva no PostgreSQL',
    empty: 'Você ainda não tem oportunidades ativas',
    emptyDetail: 'Quando uma oportunidade estiver acessível, ela aparecerá aqui.',
    errorDetail: 'A solicitação falhou. Tente novamente; exemplos nunca substituem os dados.',
    contacted: 'Contatado',
    proposal: 'Proposta',
    pending_approval: 'Aprovação pendente',
    won_simulated: 'Ganha — simulação',
    won: 'Ganha oficial',
    lost: 'Perdida',
    manual: 'Manual',
    import: 'Importação',
    status: 'Estado',
    open: 'Abertas',
    closed: 'Fechadas',
    priority: 'Prioridade',
    normal: 'Normal',
    high: 'Alta',
    inactive: 'Inativa · 7 dias',
    visibility: 'Visibilidade',
    private: 'Privada',
    team: 'Equipe',
    shared: 'Compartilhada',
    recipients: 'Destinatários autorizados (UUID separados por vírgula)',
    sessionCode: 'Código de sessão local',
    signIn: 'Iniciar sessão local',
    detailPending: 'Detalhes e ações persistentes estão disponíveis conforme sua autorização.',
    add_collaborator: 'Adicionar colaborador',
    remove_collaborator: 'Remover colaborador',
    collaborators: 'Colaboradores',
    activity: 'Registrar atividade',
    activities: 'Atividades',
    call: 'Ligação interna',
    message: 'Mensagem interna',
    occurredAt: 'Data da atividade',
    summary: 'Resumo',
    userId: 'Usuário autorizado (UUID)',
    access: 'Escopo',
    read: 'Somente leitura',
    update: 'Leitura e atualização',
    until: 'Acesso até',
    set_referral: 'Registrar indicação',
    referrer: 'Pessoa indicadora',
    referrerPersonId: 'Pessoa indicadora (UUID)',
  },
};
