import type { Locale } from './catalog';
const es = {
  reference: 'CRM Comercial',
  sort: 'Ordenar por',
  updated: 'Última actualización',
  direction: 'Dirección',
  asc: 'Ascendente',
  desc: 'Descendente',
  visibleColumns: 'Columnas visibles',
  noPermissions: 'Guardar o compartir una vista no concede permisos sobre los datos.',
  fixture: 'CRM conectado · PostgreSQL · Datos sintéticos',
  sourceLabel: 'Fuente: PostgreSQL de desarrollo — no oficial',
  saved: 'Vista guardada en PostgreSQL',
  empty: 'Aún no tienes oportunidades activas',
  emptyDetail: 'Cuando tengas acceso a una oportunidad, aparecerá aquí.',
  errorDetail: 'No se pudo completar la solicitud. Reintenta sin conexión de respaldo a ejemplos.',
  contacted: 'Contactado',
  proposal: 'Propuesta',
  pending_approval: 'Pendiente de aprobación',
  won_simulated: 'Ganada — simulación',
  won: 'Ganada oficial',
  lost: 'Perdida',
  manual: 'Manual',
  import: 'Importación',
  status: 'Estado',
  open: 'Abiertas',
  closed: 'Cerradas',
  priority: 'Prioridad',
  normal: 'Normal',
  high: 'Alta',
  inactive: 'Sin actividad · 7 días',
  visibility: 'Visibilidad',
  private: 'Privada',
  team: 'Equipo',
  shared: 'Compartida',
  recipients: 'Destinatarios autorizados (UUID separados por coma)',
  sessionCode: 'Código de sesión local',
  signIn: 'Iniciar sesión local',
  detailPending: 'Detalle y acciones persistentes disponibles según tu autorización.',
  add_collaborator: 'Añadir colaborador',
  remove_collaborator: 'Quitar colaborador',
  collaborators: 'Colaboradores',
  activity: 'Registrar actividad',
  activities: 'Actividades',
  call: 'Llamada interna',
  message: 'Mensaje interno',
  occurredAt: 'Fecha de la actividad',
  summary: 'Resumen',
  userId: 'Usuario autorizado (UUID)',
  access: 'Alcance',
  read: 'Solo lectura',
  update: 'Lectura y actualización',
  until: 'Acceso hasta',
  set_referral: 'Registrar referido',
  referrer: 'Persona referidora',
  referrerPersonId: 'Persona referidora (UUID)',
};
type CrmCatalog = { [K in keyof typeof es]: string };
export const crmCatalogs: Record<Locale, CrmCatalog> = {
  es,
  en: {
    reference: 'Commercial CRM',
    sort: 'Sort by',
    updated: 'Last updated',
    direction: 'Direction',
    asc: 'Ascending',
    desc: 'Descending',
    visibleColumns: 'Visible columns',
    noPermissions: 'Saving or sharing a view does not grant data access.',
    fixture: 'Connected CRM · PostgreSQL · Synthetic data',
    sourceLabel: 'Source: development PostgreSQL — unofficial',
    saved: 'View saved in PostgreSQL',
    empty: 'You do not have active opportunities yet',
    emptyDetail: 'When an opportunity is available to you, it will appear here.',
    errorDetail: 'The request failed. Retry; example data is never used as fallback.',
    contacted: 'Contacted',
    proposal: 'Proposal',
    pending_approval: 'Pending approval',
    won_simulated: 'Won — simulation',
    won: 'Official won',
    lost: 'Lost',
    manual: 'Manual',
    import: 'Import',
    status: 'Status',
    open: 'Open',
    closed: 'Closed',
    priority: 'Priority',
    normal: 'Normal',
    high: 'High',
    inactive: 'Inactive · 7 days',
    visibility: 'Visibility',
    private: 'Private',
    team: 'Team',
    shared: 'Shared',
    recipients: 'Authorized recipients (comma-separated UUIDs)',
    sessionCode: 'Local session code',
    signIn: 'Start local session',
    detailPending: 'Persistent details and actions are available according to your authorization.',
    add_collaborator: 'Add collaborator',
    remove_collaborator: 'Remove collaborator',
    collaborators: 'Collaborators',
    activity: 'Record activity',
    activities: 'Activities',
    call: 'Internal call',
    message: 'Internal message',
    occurredAt: 'Activity date',
    summary: 'Summary',
    userId: 'Authorized user (UUID)',
    access: 'Scope',
    read: 'Read only',
    update: 'Read and update',
    until: 'Access until',
    set_referral: 'Set referral',
    referrer: 'Referrer Person',
    referrerPersonId: 'Referrer Person (UUID)',
  },
  fr: {
    reference: 'CRM Commercial',
    sort: 'Trier par',
    updated: 'Dernière mise à jour',
    direction: 'Direction',
    asc: 'Croissant',
    desc: 'Décroissant',
    visibleColumns: 'Colonnes visibles',
    noPermissions: 'Enregistrer ou partager une vue ne donne aucun droit sur les données.',
    fixture: 'CRM connecté · PostgreSQL · Données synthétiques',
    sourceLabel: 'Source : PostgreSQL de développement — non officiel',
    saved: 'Vue enregistrée dans PostgreSQL',
    empty: 'Vous n’avez pas encore d’opportunités actives',
    emptyDetail: 'Lorsqu’une opportunité vous sera accessible, elle apparaîtra ici.',
    errorDetail: 'La requête a échoué. Réessayez ; les exemples ne remplacent jamais les données.',
    contacted: 'Contacté',
    proposal: 'Proposition',
    pending_approval: 'En attente d’approbation',
    won_simulated: 'Gagnée — simulation',
    won: 'Gagnée officielle',
    lost: 'Perdue',
    manual: 'Manuel',
    import: 'Importation',
    status: 'Statut',
    open: 'Ouvertes',
    closed: 'Fermées',
    priority: 'Priorité',
    normal: 'Normale',
    high: 'Haute',
    inactive: 'Inactive · 7 jours',
    visibility: 'Visibilité',
    private: 'Privée',
    team: 'Équipe',
    shared: 'Partagée',
    recipients: 'Destinataires autorisés (UUID séparés par des virgules)',
    sessionCode: 'Code de session locale',
    signIn: 'Ouvrir une session locale',
    detailPending: 'Les détails et actions persistants sont disponibles selon votre autorisation.',
    add_collaborator: 'Ajouter un collaborateur',
    remove_collaborator: 'Retirer le collaborateur',
    collaborators: 'Collaborateurs',
    activity: 'Enregistrer une activité',
    activities: 'Activités',
    call: 'Appel interne',
    message: 'Message interne',
    occurredAt: 'Date de l’activité',
    summary: 'Résumé',
    userId: 'Utilisateur autorisé (UUID)',
    access: 'Périmètre',
    read: 'Lecture seule',
    update: 'Lecture et modification',
    until: 'Accès jusqu’au',
    set_referral: 'Définir la recommandation',
    referrer: 'Personne référente',
    referrerPersonId: 'Personne référente (UUID)',
  },
  pt: {
    reference: 'CRM Comercial',
    sort: 'Ordenar por',
    updated: 'Última atualização',
    direction: 'Direção',
    asc: 'Crescente',
    desc: 'Decrescente',
    visibleColumns: 'Colunas visíveis',
    noPermissions: 'Salvar ou compartilhar uma visualização não concede acesso aos dados.',
    fixture: 'CRM conectado · PostgreSQL · Dados sintéticos',
    sourceLabel: 'Fonte: PostgreSQL de desenvolvimento — não oficial',
    saved: 'Visualização salva no PostgreSQL',
    empty: 'Você ainda não tem oportunidades ativas',
    emptyDetail: 'Quando uma oportunidade estiver acessível, ela aparecerá aqui.',
    errorDetail: 'A solicitação falhou. Tente novamente; exemplos nunca substituem os dados.',
    contacted: 'Contatado',
    proposal: 'Proposta',
    pending_approval: 'Aprovação pendente',
    won_simulated: 'Ganha — simulação',
    won: 'Ganha oficial',
    lost: 'Perdida',
    manual: 'Manual',
    import: 'Importação',
    status: 'Estado',
    open: 'Abertas',
    closed: 'Fechadas',
    priority: 'Prioridade',
    normal: 'Normal',
    high: 'Alta',
    inactive: 'Inativa · 7 dias',
    visibility: 'Visibilidade',
    private: 'Privada',
    team: 'Equipe',
    shared: 'Compartilhada',
    recipients: 'Destinatários autorizados (UUID separados por vírgula)',
    sessionCode: 'Código de sessão local',
    signIn: 'Iniciar sessão local',
    detailPending: 'Detalhes e ações persistentes estão disponíveis conforme sua autorização.',
    add_collaborator: 'Adicionar colaborador',
    remove_collaborator: 'Remover colaborador',
    collaborators: 'Colaboradores',
    activity: 'Registrar atividade',
    activities: 'Atividades',
    call: 'Ligação interna',
    message: 'Mensagem interna',
    occurredAt: 'Data da atividade',
    summary: 'Resumo',
    userId: 'Usuário autorizado (UUID)',
    access: 'Escopo',
    read: 'Somente leitura',
    update: 'Leitura e atualização',
    until: 'Acesso até',
    set_referral: 'Registrar indicação',
    referrer: 'Pessoa indicadora',
    referrerPersonId: 'Pessoa indicadora (UUID)',
  },
};
