import type { Locale } from './catalog';
const es = {
  reference: 'CRM Comercial',
  sort: 'Ordenar por',
  updated: 'Última actualización',
  direction: 'Dirección',
  asc: 'Ascendente',
  desc: 'Descendente',
  visibleColumns: 'Columnas visibles',
  noPermissions: 'Guardar o compartir una vista no concede permisos sobre los datos.',
  fixture: 'CRM conectado · PostgreSQL · Datos sintéticos',
  sourceLabel: 'Fuente: PostgreSQL de desarrollo — no oficial',
  saved: 'Vista guardada en PostgreSQL',
  emptyDetail: 'No hay oportunidades accesibles. Prueba otros filtros.',
  errorDetail: 'No se pudo completar la solicitud. Reintenta sin conexión de respaldo a ejemplos.',
  contacted: 'Contactado',
  proposal: 'Propuesta',
  pending_approval: 'Pendiente de aprobación',
  won_simulated: 'Ganada — simulación',
  won: 'Ganada oficial',
  lost: 'Perdida',
  manual: 'Manual',
  import: 'Importación',
  status: 'Estado',
  open: 'Abiertas',
  closed: 'Cerradas',
  priority: 'Prioridad',
  normal: 'Normal',
  high: 'Alta',
  inactive: 'Sin actividad · 7 días',
  visibility: 'Visibilidad',
  private: 'Privada',
  team: 'Equipo',
  shared: 'Compartida',
  recipients: 'Destinatarios autorizados (UUID separados por coma)',
  sessionCode: 'Código de sesión local',
  signIn: 'Iniciar sesión local',
  detailPending: 'Detalle y acciones persistentes: pendientes de U4. Esta tabla es de consulta.',
};
type CrmCatalog = { [K in keyof typeof es]: string };
export const crmCatalogs: Record<Locale, CrmCatalog> = {
  es,
  en: {
    reference: 'Commercial CRM',
    sort: 'Sort by',
    updated: 'Last updated',
    direction: 'Direction',
    asc: 'Ascending',
    desc: 'Descending',
    visibleColumns: 'Visible columns',
    noPermissions: 'Saving or sharing a view does not grant data access.',
    fixture: 'Connected CRM · PostgreSQL · Synthetic data',
    sourceLabel: 'Source: development PostgreSQL — unofficial',
    saved: 'View saved in PostgreSQL',
    emptyDetail: 'No accessible opportunities. Try different filters.',
    errorDetail: 'The request failed. Retry; example data is never used as fallback.',
    contacted: 'Contacted',
    proposal: 'Proposal',
    pending_approval: 'Pending approval',
    won_simulated: 'Won — simulation',
    won: 'Official won',
    lost: 'Lost',
    manual: 'Manual',
    import: 'Import',
    status: 'Status',
    open: 'Open',
    closed: 'Closed',
    priority: 'Priority',
    normal: 'Normal',
    high: 'High',
    inactive: 'Inactive · 7 days',
    visibility: 'Visibility',
    private: 'Private',
    team: 'Team',
    shared: 'Shared',
    recipients: 'Authorized recipients (comma-separated UUIDs)',
    sessionCode: 'Local session code',
    signIn: 'Start local session',
    detailPending: 'Persistent details and actions await U4. This table is read-only.',
  },
  fr: {
    reference: 'CRM Commercial',
    sort: 'Trier par',
    updated: 'Dernière mise à jour',
    direction: 'Direction',
    asc: 'Croissant',
    desc: 'Décroissant',
    visibleColumns: 'Colonnes visibles',
    noPermissions: 'Enregistrer ou partager une vue ne donne aucun droit sur les données.',
    fixture: 'CRM connecté · PostgreSQL · Données synthétiques',
    sourceLabel: 'Source : PostgreSQL de développement — non officiel',
    saved: 'Vue enregistrée dans PostgreSQL',
    emptyDetail: 'Aucune opportunité accessible. Essayez d’autres filtres.',
    errorDetail: 'La requête a échoué. Réessayez ; les exemples ne remplacent jamais les données.',
    contacted: 'Contacté',
    proposal: 'Proposition',
    pending_approval: 'En attente d’approbation',
    won_simulated: 'Gagnée — simulation',
    won: 'Gagnée officielle',
    lost: 'Perdue',
    manual: 'Manuel',
    import: 'Importation',
    status: 'Statut',
    open: 'Ouvertes',
    closed: 'Fermées',
    priority: 'Priorité',
    normal: 'Normale',
    high: 'Haute',
    inactive: 'Inactive · 7 jours',
    visibility: 'Visibilité',
    private: 'Privée',
    team: 'Équipe',
    shared: 'Partagée',
    recipients: 'Destinataires autorisés (UUID séparés par des virgules)',
    sessionCode: 'Code de session locale',
    signIn: 'Ouvrir une session locale',
    detailPending: 'Détails et actions persistants en attente de U4. Tableau en lecture seule.',
  },
  pt: {
    reference: 'CRM Comercial',
    sort: 'Ordenar por',
    updated: 'Última atualização',
    direction: 'Direção',
    asc: 'Crescente',
    desc: 'Decrescente',
    visibleColumns: 'Colunas visíveis',
    noPermissions: 'Salvar ou compartilhar uma visualização não concede acesso aos dados.',
    fixture: 'CRM conectado · PostgreSQL · Dados sintéticos',
    sourceLabel: 'Fonte: PostgreSQL de desenvolvimento — não oficial',
    saved: 'Visualização salva no PostgreSQL',
    emptyDetail: 'Nenhuma oportunidade acessível. Tente outros filtros.',
    errorDetail: 'A solicitação falhou. Tente novamente; exemplos nunca substituem os dados.',
    contacted: 'Contatado',
    proposal: 'Proposta',
    pending_approval: 'Aprovação pendente',
    won_simulated: 'Ganha — simulação',
    won: 'Ganha oficial',
    lost: 'Perdida',
    manual: 'Manual',
    import: 'Importação',
    status: 'Estado',
    open: 'Abertas',
    closed: 'Fechadas',
    priority: 'Prioridade',
    normal: 'Normal',
    high: 'Alta',
    inactive: 'Inativa · 7 dias',
    visibility: 'Visibilidade',
    private: 'Privada',
    team: 'Equipe',
    shared: 'Compartilhada',
    recipients: 'Destinatários autorizados (UUID separados por vírgula)',
    sessionCode: 'Código de sessão local',
    signIn: 'Iniciar sessão local',
    detailPending: 'Detalhes e ações persistentes aguardam U4. Esta tabela é somente leitura.',
  },
};
