import type { Locale } from './catalog';

const es = {
  title: 'Visitas de campo',
  subtitle: 'Visitas y siguientes acciones autorizadas',
  field: 'Campo',
  agenda: 'Agenda',
  commercial: 'CRM Comercial',
  recruiting: 'CRM Reclutamiento',
  workspace: 'Espacio conectado',
  connected: 'Datos persistentes PostgreSQL',
  locale: 'Idioma',
  theme: 'Tema',
  system: 'Sistema',
  light: 'Claro',
  dark: 'Oscuro',
  today: 'Hoy',
  upcoming: 'Próximas',
  date: 'Fecha',
  mine: 'Mías',
  all: 'Todas',
  status: 'Estado',
  planned: 'Planificada',
  in_progress: 'En curso',
  completed: 'Completada',
  cancelled: 'Cancelada',
  no_show: 'No asistió',
  create: 'Nueva visita',
  detail: 'Detalle de visita',
  close: 'Cerrar',
  purpose: 'Propósito',
  schedule: 'Programada',
  owner: 'Responsable',
  appointment: 'Cita vinculada',
  openAgenda: 'Abrir Agenda',
  person: 'Persona autorizada',
  opportunity: 'Oportunidad autorizada',
  travel: 'Traslado y preparación',
  origin: 'Origen',
  destination: 'Destino',
  travelMinutes: 'Minutos de traslado',
  preparationMinutes: 'Minutos de preparación',
  actualStart: 'Inicio real',
  actualEnd: 'Fin real',
  outcome: 'Resultado',
  notes: 'Notas',
  location: 'Evidencia de ubicación autorizada',
  locationPurpose: 'Ubicación opcional solo para esta acción; sin seguimiento continuo.',
  captureLocation: 'Solicitar ubicación para esta acción',
  locationDenied: 'No se obtuvo ubicación. Puedes continuar sin ella.',
  locationRestricted: 'La acción con ubicación no fue autorizada. Puedes reintentar sin ella.',
  continueWithoutLocation: 'Continuar sin ubicación',
  checkIn: 'Iniciar visita',
  checkOut: 'Finalizar visita',
  cancel: 'Cancelar visita',
  noShow: 'Marcar no asistió',
  save: 'Guardar',
  confirmClose: 'Confirmar cierre',
  history: 'Historial',
  created: 'Visita creada',
  updated: 'Visita actualizada',
  checked_in: 'Inicio registrado',
  checked_out: 'Cierre registrado',
  filters: 'Filtros',
  clear: 'Limpiar filtros',
  records: 'visitas',
  loading: 'Cargando visitas',
  empty: 'Aún no hay visitas',
  noResults: 'Sin resultados para estos filtros',
  forbidden: 'Acceso denegado',
  forbiddenDetail: 'Tu permiso actual no permite ver visitas.',
  notFound: 'Visita no disponible',
  conflict: 'La visita cambió. Se cargaron datos recientes.',
  invalid: 'Revisa los datos o la transición.',
  unavailable: 'Visitas no disponibles temporalmente',
  success: 'Cambio guardado',
  retry: 'Reintentar',
  sessionCode: 'Código de sesión local',
  signIn: 'Iniciar sesión local',
  collapse: 'Contraer navegación',
  expand: 'Expandir navegación',
  invalidTime: 'Hora local inválida para la zona elegida',
  timezone: 'Zona horaria',
  synthetic: 'Laboratorio local con datos sintéticos',
};
const en: typeof es = {
  title: 'Field visits',
  subtitle: 'Authorized visits and next actions',
  field: 'Field',
  agenda: 'Agenda',
  commercial: 'Commercial CRM',
  recruiting: 'Recruiting CRM',
  workspace: 'Connected workspace',
  connected: 'Persistent PostgreSQL data',
  locale: 'Language',
  theme: 'Theme',
  system: 'System',
  light: 'Light',
  dark: 'Dark',
  today: 'Today',
  upcoming: 'Upcoming',
  date: 'Date',
  mine: 'Mine',
  all: 'All',
  status: 'Status',
  planned: 'Planned',
  in_progress: 'In progress',
  completed: 'Completed',
  cancelled: 'Cancelled',
  no_show: 'No-show',
  create: 'New visit',
  detail: 'Visit detail',
  close: 'Close',
  purpose: 'Purpose',
  schedule: 'Scheduled',
  owner: 'Owner',
  appointment: 'Linked appointment',
  openAgenda: 'Open Agenda',
  person: 'Authorized person',
  opportunity: 'Authorized opportunity',
  travel: 'Travel and preparation',
  origin: 'Origin',
  destination: 'Destination',
  travelMinutes: 'Travel minutes',
  preparationMinutes: 'Preparation minutes',
  actualStart: 'Actual start',
  actualEnd: 'Actual end',
  outcome: 'Outcome',
  notes: 'Notes',
  location: 'Authorized location evidence',
  locationPurpose: 'Optional location for this action only; no continuous tracking.',
  captureLocation: 'Request location for this action',
  locationDenied: 'Location unavailable. You can continue without it.',
  locationRestricted: 'The action with location was not authorized. You can retry without it.',
  continueWithoutLocation: 'Continue without location',
  checkIn: 'Check in',
  checkOut: 'Check out',
  cancel: 'Cancel visit',
  noShow: 'Mark no-show',
  save: 'Save',
  confirmClose: 'Confirm checkout',
  history: 'History',
  created: 'Visit created',
  updated: 'Visit updated',
  checked_in: 'Check-in recorded',
  checked_out: 'Check-out recorded',
  filters: 'Filters',
  clear: 'Clear filters',
  records: 'visits',
  loading: 'Loading visits',
  empty: 'No visits yet',
  noResults: 'No visits match these filters',
  forbidden: 'Access denied',
  forbiddenDetail: 'Your current permission does not allow visits.',
  notFound: 'Visit unavailable',
  conflict: 'This visit changed. Latest data was loaded.',
  invalid: 'Review the data or transition.',
  unavailable: 'Visits temporarily unavailable',
  success: 'Change saved',
  retry: 'Retry',
  sessionCode: 'Local session code',
  signIn: 'Sign in locally',
  collapse: 'Collapse navigation',
  expand: 'Expand navigation',
  invalidTime: 'Invalid local time',
  timezone: 'Timezone',
  synthetic: 'Local lab with synthetic data',
};
const fr: typeof es = {
  ...en,
  title: 'Visites terrain',
  subtitle: 'Visites et prochaines actions autorisées',
  field: 'Terrain',
  commercial: 'CRM Commercial',
  recruiting: 'CRM Recrutement',
  workspace: 'Espace connecté',
  connected: 'Données PostgreSQL persistantes',
  locale: 'Langue',
  theme: 'Thème',
  system: 'Système',
  light: 'Clair',
  dark: 'Sombre',
  today: "Aujourd'hui",
  upcoming: 'À venir',
  date: 'Date',
  mine: 'Mes visites',
  all: 'Toutes',
  status: 'Statut',
  planned: 'Planifiée',
  in_progress: 'En cours',
  completed: 'Terminée',
  cancelled: 'Annulée',
  no_show: 'Absent',
  create: 'Nouvelle visite',
  detail: 'Détail de la visite',
  close: 'Fermer',
  purpose: 'Objet',
  schedule: 'Prévue',
  owner: 'Responsable',
  appointment: 'Rendez-vous lié',
  openAgenda: "Ouvrir l'agenda",
  person: 'Personne autorisée',
  opportunity: 'Opportunité autorisée',
  travel: 'Trajet et préparation',
  origin: 'Origine',
  destination: 'Destination',
  travelMinutes: 'Minutes de trajet',
  preparationMinutes: 'Minutes de préparation',
  actualStart: 'Début réel',
  actualEnd: 'Fin réelle',
  outcome: 'Résultat',
  notes: 'Notes',
  location: 'Position autorisée',
  locationPurpose: 'Position facultative pour cette action uniquement ; aucun suivi continu.',
  captureLocation: 'Demander la position pour cette action',
  locationDenied: 'Position indisponible. Vous pouvez continuer sans elle.',
  locationRestricted: 'Action avec position non autorisée. Réessayez sans position.',
  continueWithoutLocation: 'Continuer sans position',
  checkIn: 'Commencer la visite',
  checkOut: 'Terminer la visite',
  cancel: 'Annuler la visite',
  noShow: 'Marquer absent',
  save: 'Enregistrer',
  confirmClose: 'Confirmer la fin',
  history: 'Historique',
  created: 'Visite créée',
  updated: 'Visite modifiée',
  checked_in: 'Début enregistré',
  checked_out: 'Fin enregistrée',
  filters: 'Filtres',
  clear: 'Effacer les filtres',
  records: 'visites',
  loading: 'Chargement des visites',
  empty: 'Aucune visite',
  noResults: 'Aucun résultat',
  forbidden: 'Accès refusé',
  forbiddenDetail: "Votre autorisation ne permet pas l'accès aux visites.",
  notFound: 'Visite indisponible',
  conflict: 'La visite a changé. Dernières données chargées.',
  invalid: 'Vérifiez les données ou la transition.',
  unavailable: 'Visites temporairement indisponibles',
  success: 'Modification enregistrée',
  retry: 'Réessayer',
  sessionCode: 'Code de session locale',
  signIn: 'Connexion locale',
  collapse: 'Réduire la navigation',
  expand: 'Développer la navigation',
  invalidTime: 'Heure locale invalide',
  timezone: 'Fuseau horaire',
  synthetic: 'Laboratoire local avec données fictives',
};
const pt: typeof es = {
  ...en,
  title: 'Visitas de campo',
  subtitle: 'Visitas e próximas ações autorizadas',
  field: 'Campo',
  commercial: 'CRM Comercial',
  recruiting: 'CRM Recrutamento',
  workspace: 'Espaço conectado',
  connected: 'Dados PostgreSQL persistentes',
  locale: 'Idioma',
  theme: 'Tema',
  system: 'Sistema',
  light: 'Claro',
  dark: 'Escuro',
  today: 'Hoje',
  upcoming: 'Próximas',
  date: 'Data',
  mine: 'Minhas',
  all: 'Todas',
  status: 'Status',
  planned: 'Planejada',
  in_progress: 'Em andamento',
  completed: 'Concluída',
  cancelled: 'Cancelada',
  no_show: 'Não compareceu',
  create: 'Nova visita',
  detail: 'Detalhe da visita',
  close: 'Fechar',
  purpose: 'Objetivo',
  schedule: 'Agendada',
  owner: 'Responsável',
  appointment: 'Compromisso vinculado',
  openAgenda: 'Abrir Agenda',
  person: 'Pessoa autorizada',
  opportunity: 'Oportunidade autorizada',
  travel: 'Deslocamento e preparação',
  origin: 'Origem',
  destination: 'Destino',
  travelMinutes: 'Minutos de deslocamento',
  preparationMinutes: 'Minutos de preparação',
  actualStart: 'Início real',
  actualEnd: 'Fim real',
  outcome: 'Resultado',
  notes: 'Notas',
  location: 'Evidência de localização autorizada',
  locationPurpose: 'Localização opcional apenas para esta ação; sem rastreamento contínuo.',
  captureLocation: 'Solicitar localização para esta ação',
  locationDenied: 'Localização indisponível. Você pode continuar sem ela.',
  locationRestricted: 'A ação com localização não foi autorizada. Tente novamente sem ela.',
  continueWithoutLocation: 'Continuar sem localização',
  checkIn: 'Iniciar visita',
  checkOut: 'Concluir visita',
  cancel: 'Cancelar visita',
  noShow: 'Marcar não compareceu',
  save: 'Salvar',
  confirmClose: 'Confirmar encerramento',
  history: 'Histórico',
  created: 'Visita criada',
  updated: 'Visita atualizada',
  checked_in: 'Início registrado',
  checked_out: 'Fim registrado',
  filters: 'Filtros',
  clear: 'Limpar filtros',
  records: 'visitas',
  loading: 'Carregando visitas',
  empty: 'Ainda não há visitas',
  noResults: 'Nenhuma visita corresponde aos filtros',
  forbidden: 'Acesso negado',
  forbiddenDetail: 'Sua permissão atual não permite ver visitas.',
  notFound: 'Visita indisponível',
  conflict: 'A visita mudou. Os dados mais recentes foram carregados.',
  invalid: 'Revise os dados ou a transição.',
  unavailable: 'Visitas temporariamente indisponíveis',
  success: 'Alteração salva',
  retry: 'Tentar novamente',
  sessionCode: 'Código de sessão local',
  signIn: 'Iniciar sessão local',
  collapse: 'Recolher navegação',
  expand: 'Expandir navegação',
  invalidTime: 'Horário local inválido',
  timezone: 'Fuso horário',
  synthetic: 'Laboratório local com dados sintéticos',
};
export const fieldCatalogs: Record<Locale, typeof es> = { es, en, fr, pt };
