import type { Locale } from './catalog';

const es = {
  title: 'CRM de Reclutamiento',
  subtitle: 'Personas y seguimiento operativo de reclutamiento',
  connected: 'Recruiting conectado · PostgreSQL · Datos sintéticos',
  sourceNote: 'Fuente: PostgreSQL de desarrollo — no oficial',
  commercial: 'CRM Comercial',
  recruiting: 'Reclutamiento',
  expand: 'Expandir navegación',
  collapse: 'Colapsar navegación',
  previous: 'Página anterior',
  nextPage: 'Página siguiente',
  workspace: 'Espacio',
  list: 'Lista',
  kanban: 'Kanban',
  all: 'Todos',
  mine: 'Míos',
  due: 'Vencidos',
  search: 'Buscar personas',
  filters: 'Filtros',
  owner: 'Responsable',
  stage: 'Etapa',
  source: 'Fuente',
  substatus: 'Subestado',
  priority: 'Prioridad operativa',
  activity: 'Actividad',
  records: 'perfiles',
  person: 'Persona',
  next: 'Próxima acción',
  updated: 'Actualizado',
  self: 'Tú',
  authorized: 'Autorizado',
  loading: 'Cargando perfiles',
  empty: 'Aún no hay perfiles de reclutamiento',
  noResults: 'No hay resultados',
  forbidden: 'Acceso denegado',
  forbiddenDetail: 'No tienes permiso para ver este espacio de reclutamiento.',
  notFound: 'Perfil no disponible',
  unavailable: 'Recruiting no está disponible',
  retry: 'Reintentar',
  clear: 'Limpiar filtros',
  sessionCode: 'Código de sesión local',
  signIn: 'Iniciar sesión local',
  unauthenticated: 'Sesión requerida',
  detail: 'Detalle de reclutamiento',
  close: 'Cerrar',
  contact: 'Contacto autorizado',
  restricted: 'PII restringida',
  appointments: 'Citas',
  interviews: 'Entrevistas',
  followups: 'Seguimientos',
  hooks: 'Training / onboarding',
  timeline: 'Actividad y auditoría',
  save: 'Guardar',
  complete: 'Completar',
  advance: 'Avanzar etapa',
  reassign: 'Reasignar',
  success: 'Cambio guardado',
  conflict: 'El perfil cambió. Se recargó la versión más reciente.',
  invalid: 'Revisa los datos del formulario.',
  appointment: 'Registrar cita',
  interview: 'Registrar entrevista',
  followup: 'Crear seguimiento',
  hook: 'Registrar enlace operativo',
  startsAt: 'Inicio',
  occurredAt: 'Fecha',
  dueAt: 'Vence',
  timezone: 'Zona horaria',
  channel: 'Canal',
  outcome: 'Resultado',
  notes: 'Notas',
  text: 'Siguiente acción',
  kind: 'Tipo',
  reference: 'Referencia opcional',
  noItems: 'Sin registros',
  operational: 'A/B/C es prioridad operativa, no un diagnóstico.',
  light: 'Claro',
  dark: 'Oscuro',
  system: 'Sistema',
  locale: 'Idioma',
  theme: 'Tema',
  new: 'Nuevo',
  initial_contact: 'Contacto inicial',
  qualified: 'Calificado',
  interview_to_schedule: 'Entrevista por agendar',
  interview_scheduled: 'Entrevista agendada',
  interviewed: 'Entrevistado',
  evaluation: 'Evaluación',
  followup_decision: 'Seguimiento / decisión',
  onboarding: 'Onboarding',
  activated: 'Activado',
  manual: 'Manual',
  import: 'Importación',
  referral: 'Referido',
  event: 'Evento',
  telemarketing: 'Telemarketing',
  upcoming: 'Próxima',
  none: 'Sin actividad',
  in_person: 'Presencial',
  phone: 'Teléfono',
  video: 'Video',
  attended: 'Asistió',
  no_show: 'No asistió',
  cancelled: 'Cancelada',
  rescheduled: 'Reagendada',
  training: 'Training',
  reassign_owner: 'Reasignar responsable',
  complete_followup: 'Completar seguimiento',
  data_validated: 'Datos validados',
  duplicate_suspected: 'Posible duplicado',
  first_contact_pending: 'Primer contacto pendiente',
  contacted: 'Contactado',
  no_answer: 'Sin respuesta',
  invalid_number: 'Número inválido',
  message_sent: 'Mensaje enviado',
  interest_qualified: 'Interés calificado',
  interview_proposed: 'Entrevista propuesta',
  confirmation_pending: 'Confirmación pendiente',
  confirmed: 'Confirmado',
  no_response: 'Sin respuesta',
  reschedule_requested: 'Reagenda solicitada',
  evaluation_pending: 'Evaluación pendiente',
  evaluated: 'Evaluado',
  nurture: 'Nutrición',
  not_interested: 'Sin interés',
  registration_started: 'Registro iniciado',
  onboarding_started: 'Onboarding iniciado',
  training_pending: 'Training pendiente',
  withdrawn: 'Retirado',
};
type Catalog = Record<keyof typeof es, string> & Record<string, string>;
const en: Catalog = {
  ...es,
  title: 'Recruiting CRM',
  subtitle: 'People and operational recruiting follow-up',
  connected: 'Connected Recruiting · PostgreSQL · Synthetic data',
  sourceNote: 'Source: development PostgreSQL — unofficial',
  commercial: 'Commercial CRM',
  recruiting: 'Recruiting',
  expand: 'Expand navigation',
  collapse: 'Collapse navigation',
  previous: 'Previous page',
  nextPage: 'Next page',
  workspace: 'Workspace',
  list: 'List',
  all: 'All',
  mine: 'Mine',
  due: 'Due',
  search: 'Search people',
  filters: 'Filters',
  owner: 'Owner',
  stage: 'Stage',
  source: 'Source',
  substatus: 'Operational substatus',
  priority: 'Operational priority',
  activity: 'Activity',
  records: 'profiles',
  person: 'Person',
  next: 'Next action',
  updated: 'Updated',
  self: 'You',
  authorized: 'Authorized',
  loading: 'Loading profiles',
  empty: 'No recruiting profiles yet',
  noResults: 'No results',
  forbidden: 'Access denied',
  forbiddenDetail: 'You cannot access this recruiting workspace.',
  notFound: 'Profile unavailable',
  unavailable: 'Recruiting is unavailable',
  retry: 'Retry',
  clear: 'Clear filters',
  sessionCode: 'Local session code',
  signIn: 'Start local session',
  unauthenticated: 'Session required',
  detail: 'Recruiting detail',
  close: 'Close',
  contact: 'Authorized contact',
  restricted: 'PII restricted',
  appointments: 'Appointments',
  interviews: 'Interviews',
  followups: 'Follow-ups',
  hooks: 'Training / onboarding',
  timeline: 'Activity and audit',
  save: 'Save',
  complete: 'Complete',
  advance: 'Advance stage',
  reassign: 'Reassign',
  success: 'Change saved',
  conflict: 'The profile changed. The latest version was loaded.',
  invalid: 'Check the form data.',
  appointment: 'Record appointment',
  interview: 'Record interview',
  followup: 'Create follow-up',
  hook: 'Record operational link',
  startsAt: 'Starts',
  occurredAt: 'Date',
  dueAt: 'Due',
  timezone: 'Timezone',
  channel: 'Channel',
  outcome: 'Outcome',
  notes: 'Notes',
  text: 'Next action',
  kind: 'Type',
  reference: 'Optional reference',
  noItems: 'No records',
  operational: 'A/B/C is operational priority, not a diagnosis.',
  light: 'Light',
  dark: 'Dark',
  system: 'System',
  locale: 'Language',
  theme: 'Theme',
  new: 'New',
  initial_contact: 'Initial contact',
  qualified: 'Qualified',
  interview_to_schedule: 'Interview to schedule',
  interview_scheduled: 'Interview scheduled',
  interviewed: 'Interviewed',
  evaluation: 'Evaluation',
  followup_decision: 'Follow-up / decision',
  onboarding: 'Onboarding',
  activated: 'Activated',
  manual: 'Manual',
  import: 'Import',
  referral: 'Referral',
  event: 'Event',
  telemarketing: 'Telemarketing',
  upcoming: 'Upcoming',
  none: 'No activity',
  in_person: 'In person',
  phone: 'Phone',
  video: 'Video',
  attended: 'Attended',
  no_show: 'No-show',
  cancelled: 'Cancelled',
  rescheduled: 'Rescheduled',
  training: 'Training',
  reassign_owner: 'Reassign owner',
  complete_followup: 'Complete follow-up',
  data_validated: 'Data validated',
  duplicate_suspected: 'Possible duplicate',
  first_contact_pending: 'First contact pending',
  contacted: 'Contacted',
  no_answer: 'No answer',
  invalid_number: 'Invalid number',
  message_sent: 'Message sent',
  interest_qualified: 'Interest qualified',
  interview_proposed: 'Interview proposed',
  confirmation_pending: 'Confirmation pending',
  confirmed: 'Confirmed',
  no_response: 'No response',
  reschedule_requested: 'Reschedule requested',
  evaluation_pending: 'Evaluation pending',
  evaluated: 'Evaluated',
  nurture: 'Nurture',
  not_interested: 'Not interested',
  registration_started: 'Registration started',
  onboarding_started: 'Onboarding started',
  training_pending: 'Training pending',
  withdrawn: 'Withdrawn',
};
const fr: Catalog = {
  ...en,
  title: 'CRM Recrutement',
  subtitle: 'Personnes et suivi opérationnel du recrutement',
  connected: 'Recrutement connecté · PostgreSQL · Données synthétiques',
  sourceNote: 'Source : PostgreSQL de développement — non officielle',
  commercial: 'CRM Commercial',
  recruiting: 'Recrutement',
  expand: 'Développer la navigation',
  collapse: 'Réduire la navigation',
  previous: 'Page précédente',
  nextPage: 'Page suivante',
  workspace: 'Espace',
  list: 'Liste',
  all: 'Tous',
  mine: 'Mes profils',
  due: 'En retard',
  search: 'Rechercher des personnes',
  filters: 'Filtres',
  owner: 'Responsable',
  stage: 'Étape',
  source: 'Source',
  substatus: 'Sous-statut opérationnel',
  priority: 'Priorité opérationnelle',
  activity: 'Activité',
  records: 'profils',
  person: 'Personne',
  next: 'Prochaine action',
  updated: 'Mis à jour',
  self: 'Vous',
  authorized: 'Autorisé',
  loading: 'Chargement des profils',
  empty: 'Aucun profil de recrutement',
  noResults: 'Aucun résultat',
  forbidden: 'Accès refusé',
  forbiddenDetail: 'Vous n’avez pas accès à cet espace de recrutement.',
  notFound: 'Profil indisponible',
  unavailable: 'Recrutement indisponible',
  retry: 'Réessayer',
  clear: 'Effacer les filtres',
  sessionCode: 'Code de session locale',
  signIn: 'Ouvrir la session locale',
  unauthenticated: 'Session requise',
  detail: 'Détail recrutement',
  close: 'Fermer',
  contact: 'Contact autorisé',
  restricted: 'Données personnelles limitées',
  appointments: 'Rendez-vous',
  interviews: 'Entretiens',
  followups: 'Suivis',
  hooks: 'Formation / intégration',
  timeline: 'Activité et audit',
  save: 'Enregistrer',
  complete: 'Terminer',
  advance: 'Avancer l’étape',
  reassign: 'Réaffecter',
  success: 'Modification enregistrée',
  conflict: 'Le profil a changé. La version récente a été chargée.',
  invalid: 'Vérifiez les données.',
  appointment: 'Ajouter un rendez-vous',
  interview: 'Ajouter un entretien',
  followup: 'Créer un suivi',
  hook: 'Ajouter un lien opérationnel',
  startsAt: 'Début',
  occurredAt: 'Date',
  dueAt: 'Échéance',
  timezone: 'Fuseau horaire',
  channel: 'Canal',
  outcome: 'Résultat',
  notes: 'Notes',
  text: 'Prochaine action',
  kind: 'Type',
  reference: 'Référence facultative',
  noItems: 'Aucun élément',
  operational: 'A/B/C indique une priorité opérationnelle, pas un diagnostic.',
  light: 'Clair',
  dark: 'Sombre',
  system: 'Système',
  locale: 'Langue',
  theme: 'Thème',
  new: 'Nouveau',
  initial_contact: 'Premier contact',
  qualified: 'Qualifié',
  interview_to_schedule: 'Entretien à planifier',
  interview_scheduled: 'Entretien planifié',
  interviewed: 'Entretien réalisé',
  evaluation: 'Évaluation',
  followup_decision: 'Suivi / décision',
  onboarding: 'Intégration',
  activated: 'Activé',
  manual: 'Manuel',
  import: 'Importation',
  referral: 'Recommandation',
  event: 'Événement',
  telemarketing: 'Télémarketing',
  upcoming: 'À venir',
  none: 'Aucune activité',
  in_person: 'En personne',
  phone: 'Téléphone',
  video: 'Vidéo',
  attended: 'Présent',
  no_show: 'Absent',
  cancelled: 'Annulé',
  rescheduled: 'Replanifié',
  training: 'Formation',
  reassign_owner: 'Réaffecter le responsable',
  complete_followup: 'Terminer le suivi',
  data_validated: 'Données validées',
  duplicate_suspected: 'Doublon possible',
  first_contact_pending: 'Premier contact en attente',
  contacted: 'Contacté',
  no_answer: 'Sans réponse',
  invalid_number: 'Numéro invalide',
  message_sent: 'Message envoyé',
  interest_qualified: 'Intérêt qualifié',
  interview_proposed: 'Entretien proposé',
  confirmation_pending: 'Confirmation en attente',
  confirmed: 'Confirmé',
  no_response: 'Sans réponse',
  reschedule_requested: 'Report demandé',
  evaluation_pending: 'Évaluation en attente',
  evaluated: 'Évalué',
  nurture: 'Suivi long terme',
  not_interested: 'Pas intéressé',
  registration_started: 'Inscription commencée',
  onboarding_started: 'Intégration commencée',
  training_pending: 'Formation en attente',
  withdrawn: 'Retiré',
};
const pt: Catalog = {
  ...en,
  title: 'CRM de Recrutamento',
  subtitle: 'Pessoas e acompanhamento operacional de recrutamento',
  connected: 'Recrutamento conectado · PostgreSQL · Dados sintéticos',
  sourceNote: 'Fonte: PostgreSQL de desenvolvimento — não oficial',
  commercial: 'CRM Comercial',
  recruiting: 'Recrutamento',
  expand: 'Expandir navegação',
  collapse: 'Recolher navegação',
  previous: 'Página anterior',
  nextPage: 'Próxima página',
  workspace: 'Espaço',
  list: 'Lista',
  all: 'Todos',
  mine: 'Meus',
  due: 'Vencidos',
  search: 'Buscar pessoas',
  filters: 'Filtros',
  owner: 'Responsável',
  stage: 'Etapa',
  source: 'Origem',
  substatus: 'Substatus operacional',
  priority: 'Prioridade operacional',
  activity: 'Atividade',
  records: 'perfis',
  person: 'Pessoa',
  next: 'Próxima ação',
  updated: 'Atualizado',
  self: 'Você',
  authorized: 'Autorizado',
  loading: 'Carregando perfis',
  empty: 'Ainda não há perfis de recrutamento',
  noResults: 'Sem resultados',
  forbidden: 'Acesso negado',
  forbiddenDetail: 'Você não tem acesso a este espaço de recrutamento.',
  notFound: 'Perfil indisponível',
  unavailable: 'Recrutamento indisponível',
  retry: 'Tentar novamente',
  clear: 'Limpar filtros',
  sessionCode: 'Código de sessão local',
  signIn: 'Iniciar sessão local',
  unauthenticated: 'Sessão necessária',
  detail: 'Detalhe de recrutamento',
  close: 'Fechar',
  contact: 'Contato autorizado',
  restricted: 'PII restrita',
  appointments: 'Compromissos',
  interviews: 'Entrevistas',
  followups: 'Acompanhamentos',
  hooks: 'Treinamento / onboarding',
  timeline: 'Atividade e auditoria',
  save: 'Salvar',
  complete: 'Concluir',
  advance: 'Avançar etapa',
  reassign: 'Reatribuir',
  success: 'Alteração salva',
  conflict: 'O perfil mudou. A versão mais recente foi carregada.',
  invalid: 'Revise os dados.',
  appointment: 'Registrar compromisso',
  interview: 'Registrar entrevista',
  followup: 'Criar acompanhamento',
  hook: 'Registrar vínculo operacional',
  startsAt: 'Início',
  occurredAt: 'Data',
  dueAt: 'Vencimento',
  timezone: 'Fuso horário',
  channel: 'Canal',
  outcome: 'Resultado',
  notes: 'Notas',
  text: 'Próxima ação',
  kind: 'Tipo',
  reference: 'Referência opcional',
  noItems: 'Sem registros',
  operational: 'A/B/C é prioridade operacional, não um diagnóstico.',
  light: 'Claro',
  dark: 'Escuro',
  system: 'Sistema',
  locale: 'Idioma',
  theme: 'Tema',
  new: 'Novo',
  initial_contact: 'Contato inicial',
  qualified: 'Qualificado',
  interview_to_schedule: 'Entrevista a agendar',
  interview_scheduled: 'Entrevista agendada',
  interviewed: 'Entrevistado',
  evaluation: 'Avaliação',
  followup_decision: 'Acompanhamento / decisão',
  onboarding: 'Onboarding',
  activated: 'Ativado',
  manual: 'Manual',
  import: 'Importação',
  referral: 'Indicação',
  event: 'Evento',
  telemarketing: 'Telemarketing',
  upcoming: 'Próxima',
  none: 'Sem atividade',
  in_person: 'Presencial',
  phone: 'Telefone',
  video: 'Vídeo',
  attended: 'Compareceu',
  no_show: 'Não compareceu',
  cancelled: 'Cancelada',
  rescheduled: 'Reagendada',
  training: 'Treinamento',
  reassign_owner: 'Reatribuir responsável',
  complete_followup: 'Concluir acompanhamento',
  data_validated: 'Dados validados',
  duplicate_suspected: 'Possível duplicidade',
  first_contact_pending: 'Primeiro contato pendente',
  contacted: 'Contatado',
  no_answer: 'Sem resposta',
  invalid_number: 'Número inválido',
  message_sent: 'Mensagem enviada',
  interest_qualified: 'Interesse qualificado',
  interview_proposed: 'Entrevista proposta',
  confirmation_pending: 'Confirmação pendente',
  confirmed: 'Confirmado',
  no_response: 'Sem resposta',
  reschedule_requested: 'Reagendamento solicitado',
  evaluation_pending: 'Avaliação pendente',
  evaluated: 'Avaliado',
  nurture: 'Nutrição',
  not_interested: 'Sem interesse',
  registration_started: 'Cadastro iniciado',
  onboarding_started: 'Onboarding iniciado',
  training_pending: 'Treinamento pendente',
  withdrawn: 'Retirado',
};

export const recruitingCatalogs: Record<Locale, Catalog> = { es, en, fr, pt };
