import type { Locale } from './catalog';
const words = {
  detail: [
    'Detalle de oportunidad',
    'Opportunity detail',
    'Détail de l’opportunité',
    'Detalhe da oportunidade',
  ],
  actions: ['Acciones', 'Actions', 'Actions', 'Ações'],
  stage: ['Cambiar etapa', 'Change stage', 'Changer d’étape', 'Alterar etapa'],
  appointment: [
    'Agendar cita',
    'Schedule appointment',
    'Planifier un rendez-vous',
    'Agendar visita',
  ],
  demo: [
    'Registrar resultado de demo',
    'Record demo outcome',
    'Enregistrer le résultat de démo',
    'Registrar resultado da demonstração',
  ],
  quote: [
    'Registrar cotización simulada',
    'Record simulated quote',
    'Enregistrer un devis simulé',
    'Registrar cotação simulada',
  ],
  submit_order: [
    'Enviar pedido simulado',
    'Submit simulated order',
    'Soumettre la commande simulée',
    'Enviar pedido simulado',
  ],
  reconcile_mock: [
    'Conciliar simulación',
    'Reconcile simulation',
    'Rapprocher la simulation',
    'Conciliar simulação',
  ],
  delivery: [
    'Registrar entrega',
    'Record delivery',
    'Enregistrer la livraison',
    'Registrar entrega',
  ],
  curation: [
    'Completar curación',
    'Complete curation',
    'Terminer la préparation',
    'Concluir preparação',
  ],
  entry: [
    'Añadir nota o tarea',
    'Add note or task',
    'Ajouter une note ou tâche',
    'Adicionar nota ou tarefa',
  ],
  complete_task: ['Completar tarea', 'Complete task', 'Terminer la tâche', 'Concluir tarefa'],
  edit_person: ['Editar persona', 'Edit person', 'Modifier la personne', 'Editar pessoa'],
  edit_contact: ['Editar contacto', 'Edit contact', 'Modifier le contact', 'Editar contato'],
  note: ['Nota', 'Note', 'Note', 'Nota'],
  task: ['Tarea', 'Task', 'Tâche', 'Tarefa'],
  objection: ['Objeción', 'Objection', 'Objection', 'Objeção'],
  commitment: ['Compromiso', 'Commitment', 'Engagement', 'Compromisso'],
  text: ['Texto', 'Text', 'Texte', 'Texto'],
  kind: ['Tipo', 'Type', 'Type', 'Tipo'],
  startsAt: ['Fecha y hora', 'Date and time', 'Date et heure', 'Data e hora'],
  timezone: ['Zona horaria', 'Time zone', 'Fuseau horaire', 'Fuso horário'],
  channel: ['Canal', 'Channel', 'Canal', 'Canal'],
  visit: ['Visita', 'Visit', 'Visite', 'Visita'],
  phone: ['Teléfono', 'Phone', 'Téléphone', 'Telefone'],
  video: ['Video', 'Video', 'Vidéo', 'Vídeo'],
  email: ['Correo', 'Email', 'Courriel', 'Email'],
  displayName: ['Nombre', 'Name', 'Nom', 'Nome'],
  product: ['Producto sintético', 'Synthetic product', 'Produit synthétique', 'Produto sintético'],
  amount: ['Importe simulado', 'Simulated amount', 'Montant simulé', 'Valor simulado'],
  currency: ['Moneda', 'Currency', 'Devise', 'Moeda'],
  dueAt: ['Vencimiento opcional', 'Optional due date', 'Échéance facultative', 'Prazo opcional'],
  outcome: ['Resultado', 'Outcome', 'Résultat', 'Resultado'],
  result: ['Resultado simulado', 'Simulated result', 'Résultat simulé', 'Resultado simulado'],
  approved: [
    'Aprobada — simulación',
    'Approved — simulation',
    'Approuvée — simulation',
    'Aprovada — simulação',
  ],
  conflict: ['Conflicto', 'Conflict', 'Conflit', 'Conflito'],
  rejected_or_cancelled: [
    'Rechazada/cancelada',
    'Rejected/cancelled',
    'Rejetée/annulée',
    'Rejeitada/cancelada',
  ],
  company_processing: [
    'En proceso — simulación',
    'Processing — simulation',
    'Traitement — simulation',
    'Processamento — simulação',
  ],
  delivered: [
    'Entregada — simulación',
    'Delivered — simulation',
    'Livrée — simulation',
    'Entregue — simulação',
  ],
  cured: [
    'Curada — simulación',
    'Cured — simulation',
    'Préparée — simulation',
    'Preparada — simulação',
  ],
  curation_pending: [
    'Curación pendiente',
    'Curation pending',
    'Préparation en attente',
    'Preparação pendente',
  ],
  customer_agreed: [
    'Cliente de acuerdo',
    'Customer agreed',
    'Client d’accord',
    'Cliente de acordo',
  ],
  purchase_intent_confirmed: [
    'Intención de compra confirmada',
    'Purchase intent confirmed',
    'Intention d’achat confirmée',
    'Intenção de compra confirmada',
  ],
  quote_requested: [
    'Cotización solicitada',
    'Quote requested',
    'Devis demandé',
    'Cotação solicitada',
  ],
  order_started: ['Pedido iniciado', 'Order started', 'Commande commencée', 'Pedido iniciado'],
  followup_required: [
    'Requiere seguimiento',
    'Follow-up required',
    'Suivi nécessaire',
    'Acompanhamento necessário',
  ],
  no_sale: ['Sin venta', 'No sale', 'Aucune vente', 'Sem venda'],
  referral_generated: [
    'Referido generado',
    'Referral generated',
    'Recommandation générée',
    'Indicação gerada',
  ],
  recruitment_interest: [
    'Interés en reclutamiento',
    'Recruitment interest',
    'Intérêt pour le recrutement',
    'Interesse em recrutamento',
  ],
  other: ['Otro', 'Other', 'Autre', 'Outro'],
  simulation: [
    'Simulación local. No es una aprobación ni una venta oficial.',
    'Local simulation. Not an official approval or sale.',
    'Simulation locale. Ni approbation ni vente officielle.',
    'Simulação local. Não é aprovação nem venda oficial.',
  ],
  recent: [
    'Historial reciente (máximo 100 por sección)',
    'Recent history (up to 100 per section)',
    'Historique récent (100 maximum par section)',
    'Histórico recente (até 100 por seção)',
  ],
  history: ['Historial', 'History', 'Historique', 'Histórico'],
  noData: [
    'Sin registros accesibles',
    'No accessible records',
    'Aucun enregistrement accessible',
    'Sem registros acessíveis',
  ],
  noContact: [
    'Contacto no disponible o no autorizado',
    'Contact unavailable or unauthorized',
    'Contact indisponible ou non autorisé',
    'Contato indisponível ou não autorizado',
  ],
  saved: [
    'Cambio confirmado en PostgreSQL',
    'Change confirmed in PostgreSQL',
    'Modification confirmée dans PostgreSQL',
    'Alteração confirmada no PostgreSQL',
  ],
  conflictHelp: [
    'El registro cambió. Recarga y revisa antes de reenviar.',
    'The record changed. Reload and review before resubmitting.',
    'L’enregistrement a changé. Rechargez et vérifiez avant de renvoyer.',
    'O registro mudou. Recarregue e revise antes de reenviar.',
  ],
  notFound: [
    'No disponible o sin permiso.',
    'Unavailable or not permitted.',
    'Indisponible ou non autorisé.',
    'Indisponível ou sem permissão.',
  ],
  invalid: [
    'Acción no válida para el estado actual. Revisa los campos.',
    'Action invalid for the current state. Check the fields.',
    'Action non valide pour l’état actuel. Vérifiez les champs.',
    'Ação inválida para o estado atual. Verifique os campos.',
  ],
  confirm: [
    'Confirmo esta acción de simulación',
    'I confirm this simulation action',
    'Je confirme cette action de simulation',
    'Confirmo esta ação de simulação',
  ],
  page: ['Página de etapa', 'Stage page', 'Page de l’étape', 'Página da etapa'],
  RPT_USER: ['Usuario RPT', 'RPT user', 'Utilisateur RPT', 'Usuário RPT'],
  MANUAL_RECONCILIATION: [
    'Conciliación manual',
    'Manual reconciliation',
    'Rapprochement manuel',
    'Conciliação manual',
  ],
  manual: ['Manual', 'Manual', 'Manuelle', 'Manual'],
  none: ['Sin próxima acción', 'No next action', 'Aucune prochaine action', 'Sem próxima ação'],
  schedule: ['Agendar cita', 'Schedule appointment', 'Planifier un rendez-vous', 'Agendar visita'],
  relationshipHealth: [
    'Salud de la relación',
    'Relationship health',
    'Santé de la relation',
    'Saúde do relacionamento',
  ],
  operationalScore: [
    'Score operativo',
    'Operational score',
    'Score opérationnel',
    'Score operacional',
  ],
  nextBestAction: [
    'Siguiente mejor acción',
    'Next best action',
    'Meilleure prochaine action',
    'Próxima melhor ação',
  ],
  rptRecommendation: [
    'Cálculo RPT · recomendación, no hecho oficial',
    'RPT calculation · recommendation, not an official fact',
    'Calcul RPT · recommandation, pas un fait officiel',
    'Cálculo RPT · recomendação, não um fato oficial',
  ],
  healthy: ['Saludable', 'Healthy', 'Saine', 'Saudável'],
  attention: ['Requiere atención', 'Needs attention', 'Attention requise', 'Requer atenção'],
  at_risk: ['En riesgo', 'At risk', 'À risque', 'Em risco'],
  recent_activity: [
    'Actividad reciente',
    'Recent activity',
    'Activité récente',
    'Atividade recente',
  ],
  recent_update: [
    'Actualización reciente',
    'Recent update',
    'Mise à jour récente',
    'Atualização recente',
  ],
  inactive_7d: [
    'Inactividad de 7 días',
    'Inactive for 7 days',
    'Inactivité de 7 jours',
    'Inatividade de 7 dias',
  ],
  inactive_14d: [
    'Inactividad de 14 días',
    'Inactive for 14 days',
    'Inactivité de 14 jours',
    'Inatividade de 14 dias',
  ],
  overdue_task: ['Tarea vencida', 'Overdue task', 'Tâche en retard', 'Tarefa vencida'],
  overdue_next_action: [
    'Próxima acción vencida',
    'Next action overdue',
    'Prochaine action en retard',
    'Próxima ação vencida',
  ],
  missing_next_action: [
    'Falta próxima acción',
    'Missing next action',
    'Prochaine action manquante',
    'Falta próxima ação',
  ],
  pending_objection: [
    'Objeción pendiente',
    'Pending objection',
    'Objection en attente',
    'Objeção pendente',
  ],
  pending_commitment: [
    'Compromiso pendiente',
    'Pending commitment',
    'Engagement en attente',
    'Compromisso pendente',
  ],
  scheduled_appointment: [
    'Cita programada',
    'Scheduled appointment',
    'Rendez-vous planifié',
    'Visita agendada',
  ],
  closed_stage: ['Etapa cerrada', 'Closed stage', 'Étape clôturée', 'Etapa encerrada'],
  stage_next_step: [
    'Siguiente paso de la etapa',
    'Stage next step',
    'Prochaine étape',
    'Próximo passo da etapa',
  ],
  prepare_appointment: [
    'Preparar cita',
    'Prepare appointment',
    'Préparer le rendez-vous',
    'Preparar visita',
  ],
  mainReasons: ['Razones principales', 'Main reasons', 'Raisons principales', 'Principais motivos'],
} satisfies Record<string, [string, string, string, string]>;
export function u4Labels(locale: Locale): Record<keyof typeof words, string> {
  const index = { es: 0, en: 1, fr: 2, pt: 3 }[locale];
  return Object.fromEntries(
    Object.entries(words).map(([key, values]) => [key, values[index]]),
  ) as Record<keyof typeof words, string>;
}
